	
		//
		// CareActivityDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class CareActivityDTO 	    {
		 
				var carePlanTemplate_oid: Int?;
				    	 
		 
				var id: Int?;
				    	 
		 
				var periodicity: TypePeriodicity?;
				    	 
		 
				var description: String?;
				    	 
		 
				var duration: Int?;
				    	 
		 
				var medication: MedicationDTO?;
				    	 
		 
				var location: String?;
				    	 
		 
				var outcomeCode: String?;
				    	 
		 
				var nutritionOrder: NutritionOrderDTO?;
				    	 
		 
				var typeActivity: TypeActivity?;
				    	 
		 
				var notification: [ComunicationDTO]?;
				    	 
		 
				var activityCode: String?;
				    	 
		 
				var name: String?;
				    	 
		 
				var appointment: AppointmentDTO?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


					dictionary["carePlanTemplate_oid"] = self.carePlanTemplate_oid;
			

				
					dictionary["id"] = self.id;
				

				
					dictionary["periodicity"] = self.periodicity?.rawValue;
				

				
					dictionary["description"] = self.description;
				

				
					dictionary["duration"] = self.duration;
				

					dictionary["medication"] = self.medication?.toDictionary() ?? NSNull();
			

				
					dictionary["location"] = self.location;
				

				
					dictionary["outcomeCode"] = self.outcomeCode;
				

					dictionary["nutritionOrder"] = self.nutritionOrder?.toDictionary() ?? NSNull();
			

				
					dictionary["typeActivity"] = self.typeActivity?.rawValue;
				

					dictionary["notification"] = NSNull();
					if (self.notification != nil)
					{
						var arrayOfDictionary: [[String : AnyObject]] = [];
						for item in self.notification!
						{
							arrayOfDictionary.append(item.toDictionary());
						}
						
						dictionary["notification"] = arrayOfDictionary;
					}
			

				
					dictionary["activityCode"] = self.activityCode;
				

				
					dictionary["name"] = self.name;
				

					dictionary["appointment"] = self.appointment?.toDictionary() ?? NSNull();
			
						
				return dictionary;
			}
		}
		
	