	
		//
		// DeviceTemplateDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class DeviceTemplateDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var name: String?;
				    	 
		 
				var property: [PropertyDTO]?;
				    	 
		 
				var command: [CommandDTO]?;
				    	 
		 
				var telemetry: [TelemetryDTO]?;
				    	 
		 
				var type: DeviceType?;
				    	 
		 
				var isEdge: Bool?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

				
					dictionary["name"] = self.name;
				

					dictionary["property"] = NSNull();
					if (self.property != nil)
					{
						var arrayOfDictionary: [[String : AnyObject]] = [];
						for item in self.property!
						{
							arrayOfDictionary.append(item.toDictionary());
						}
						
						dictionary["property"] = arrayOfDictionary;
					}
			

					dictionary["command"] = NSNull();
					if (self.command != nil)
					{
						var arrayOfDictionary: [[String : AnyObject]] = [];
						for item in self.command!
						{
							arrayOfDictionary.append(item.toDictionary());
						}
						
						dictionary["command"] = arrayOfDictionary;
					}
			

					dictionary["telemetry"] = NSNull();
					if (self.telemetry != nil)
					{
						var arrayOfDictionary: [[String : AnyObject]] = [];
						for item in self.telemetry!
						{
							arrayOfDictionary.append(item.toDictionary());
						}
						
						dictionary["telemetry"] = arrayOfDictionary;
					}
			

				
					dictionary["type"] = self.type?.rawValue;
				

				
					dictionary["isEdge"] = self.isEdge;
				
						
				return dictionary;
			}
		}
		
	