	
		//
		// EntityStateDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class EntityStateDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var virtualEntity_oid: Int?;
				    	 
		 
				var originOperations_oid: [Int]?;
				    	 
		 
				var targetOperations_oid: [Int]?;
				    	 
		 
				var type: StateType?;
				    	 
		 
				var name: String?;
				    	 
		 
				var description: String?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

					dictionary["virtualEntity_oid"] = self.virtualEntity_oid;
			

					dictionary["originOperations_oid"] = self.originOperations_oid;
			

					dictionary["targetOperations_oid"] = self.targetOperations_oid;
			

				
					dictionary["type"] = self.type?.rawValue;
				

				
					dictionary["name"] = self.name;
				

				
					dictionary["description"] = self.description;
				
						
				return dictionary;
			}
		}
		
	