	
		//
		// NutritionOrderDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class NutritionOrderDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var description: String?;
				    	 
		 
				var dietCode: String?;
				    	 
		 
				var careActivity_oid: Int?;
				    	 
		 
				var name: String?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

				
					dictionary["description"] = self.description;
				

				
					dictionary["dietCode"] = self.dietCode;
				

					dictionary["careActivity_oid"] = self.careActivity_oid;
			

				
					dictionary["name"] = self.name;
				
						
				return dictionary;
			}
		}
		
	