	
		//
		// RecipeDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class RecipeDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var name: String?;
				    	 
		 
				var isEnabled: Bool?;
				    	 
		 
				var triggers: RecipeTriggerDTO?;
				    	 
		 
				var recipeAction: [RecipeActionDTO]?;
				    	 
		 
				var ioTScenario_oid: Int?;
				    	 
		 
				var intervalTime: Double?;
				    	 
		 
				var description: String?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

				
					dictionary["name"] = self.name;
				

				
					dictionary["isEnabled"] = self.isEnabled;
				

					dictionary["triggers"] = self.triggers?.toDictionary() ?? NSNull();
			

					dictionary["recipeAction"] = NSNull();
					if (self.recipeAction != nil)
					{
						var arrayOfDictionary: [[String : AnyObject]] = [];
						for item in self.recipeAction!
						{
							arrayOfDictionary.append(item.toDictionary());
						}
						
						dictionary["recipeAction"] = arrayOfDictionary;
					}
			

					dictionary["ioTScenario_oid"] = self.ioTScenario_oid;
			

				
					dictionary["intervalTime"] = self.intervalTime;
				

				
					dictionary["description"] = self.description;
				
						
				return dictionary;
			}
		}
		
	