
package MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.enumerations;

/**
 * Code autogenerated. Do not modify this file.
 */
public enum LanguageCode
{
	// region - Literals

	Es (1)
	,	En (2)
	,	Fr (3)
	,	It (4)
	,	Pr (5)
	,	De (6)
	,	Ja (7)
	,	Ko (8)
	,	Zh (9)
;

	// endregion


	// region - Members and constructor

	private final int rawValue;

	public int getRawValue ()
	{
		return this.rawValue;
	}

	LanguageCode (int rawValue)
	{
		this.rawValue = rawValue;
	}

	// endregion


	// region - Public methods

	public static LanguageCode fromRawValue (int rawValue)
	{
		LanguageCode[] enumValues = LanguageCode.values();

		for (int i = 0; i < enumValues.length; i++)
		{
			if (enumValues[i].Compare(rawValue))
			{
				return enumValues[i];
			}
		}

		return null;
	}

	public boolean Compare (int rawValue)
	{
		return this.rawValue == rawValue;
	}

	// endregion
	
}
