
package MoSIoTGenMosIoTRESTAzure.uiModels.DTOA;

import MoSIoTGenMosIoTRESTAzure.uiModels.DTO.*;
import MoSIoTGenMosIoTRESTAzure.uiModels.DTO.utils.*;
import MoSIoTGenMosIoTRESTAzure.uiModels.DTO.enumerations.*;

import java.util.ArrayList;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Code autogenerated. Do not modify this file.
 */
public class AdaptationRequestDTOA extends DTOA
{
	// region - Members, getters and setters

	private Integer id;
	public Integer getId () { return id; }
	public void setId (Integer id) { this.id = id; }

	
	private AccessModeValue accessModeTarget;
	public AccessModeValue getAccessModeTarget () { return accessModeTarget; }
	public void setAccessModeTarget (AccessModeValue accessModeTarget) { this.accessModeTarget = accessModeTarget; }
	
	private LanguageCode languageOfAdaptation;
	public LanguageCode getLanguageOfAdaptation () { return languageOfAdaptation; }
	public void setLanguageOfAdaptation (LanguageCode languageOfAdaptation) { this.languageOfAdaptation = languageOfAdaptation; }
	
	private String description;
	public String getDescription () { return description; }
	public void setDescription (String description) { this.description = description; }
	
	
	
	
	// endregion
	
	
	
	// region - Constructor and JSON <-> DTOA <-> DTO
	
	public AdaptationRequestDTOA ()
	{
		// Empty constructor
	}
	
	@Override
	public void setFromJSON (JSONObject json)
	{
		try
		{
			if (!JSONObject.NULL.equals(json.opt("Id")))
			{
				this.id = (Integer) json.opt("Id");
			}
			

			if (!JSONObject.NULL.equals(json.opt("AccessModeTarget")))
			{
				int enumRawValue = (int) json.opt("AccessModeTarget");
				this.accessModeTarget = AccessModeValue.fromRawValue(enumRawValue);
			 
			}

			if (!JSONObject.NULL.equals(json.opt("LanguageOfAdaptation")))
			{
				int enumRawValue = (int) json.opt("LanguageOfAdaptation");
				this.languageOfAdaptation = LanguageCode.fromRawValue(enumRawValue);
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Description")))
			{
			 
				this.description = (String) json.opt("Description");
			 
			}
			
			
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
	}
	
	public JSONObject toJSON ()
	{
		JSONObject json = new JSONObject();
		
		try
		{
			if (this.id != null){
				json.put("Id", this.id);
			}
			
		
		  if (this.accessModeTarget != null)
			json.put("AccessModeTarget", this.accessModeTarget.getRawValue());
		
		
		  if (this.languageOfAdaptation != null)
			json.put("LanguageOfAdaptation", this.languageOfAdaptation.getRawValue());
		
		
		  if (this.description != null)
			json.put("Description", this.description);
		
			
			
		}
		catch (JSONException e)
		{
			e.printStackTrace();
		}
		
		return json;
	}
	
	@Override 
	public IDTO toDTO ()
	{
		AdaptationRequestDTO dto = new AdaptationRequestDTO ();
		
		// Attributes
		
	dto.setId (this.getId());

		
	dto.setAccessModeTarget (this.getAccessModeTarget());

	dto.setLanguageOfAdaptation (this.getLanguageOfAdaptation());

	dto.setDescription (this.getDescription());

		
		
		// Roles
		
		
		return dto;
	}

	// endregion
}

	