
package MoSIoTGenMosIoTRESTAzure.uiModels.DTOA;

import MoSIoTGenMosIoTRESTAzure.uiModels.DTO.*;
import MoSIoTGenMosIoTRESTAzure.uiModels.DTO.utils.*;
import MoSIoTGenMosIoTRESTAzure.uiModels.DTO.enumerations.*;

import java.util.ArrayList;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Code autogenerated. Do not modify this file.
 */
public class CarePlanTemplateDTOA extends DTOA
{
	// region - Members, getters and setters

	private Integer id;
	public Integer getId () { return id; }
	public void setId (Integer id) { this.id = id; }

	
	private CareStatus status;
	public CareStatus getStatus () { return status; }
	public void setStatus (CareStatus status) { this.status = status; }
	
	private CarePlanIntent intent;
	public CarePlanIntent getIntent () { return intent; }
	public void setIntent (CarePlanIntent intent) { this.intent = intent; }
	
	private String title;
	public String getTitle () { return title; }
	public void setTitle (String title) { this.title = title; }
	
	private java.util.Date modified;
	public java.util.Date getModified () { return modified; }
	public void setModified (java.util.Date modified) { this.modified = modified; }
	
	private Integer durationDays;
	public Integer getDurationDays () { return durationDays; }
	public void setDurationDays (Integer durationDays) { this.durationDays = durationDays; }
	
	private String name;
	public String getName () { return name; }
	public void setName (String name) { this.name = name; }
	
	private String description;
	public String getDescription () { return description; }
	public void setDescription (String description) { this.description = description; }
	
	
	/* Rol: CarePlanTemplate o--> CareActivity */
	private ArrayList<CareActivityDTOA> careActivities;
	public ArrayList<CareActivityDTOA> getCareActivities () { return careActivities; }
	public void setCareActivities (ArrayList<CareActivityDTOA> careActivities) { this.careActivities = careActivities; }

	/* Rol: CarePlanTemplate o--> Goal */
	private ArrayList<GoalDTOA> goals;
	public ArrayList<GoalDTOA> getGoals () { return goals; }
	public void setGoals (ArrayList<GoalDTOA> goals) { this.goals = goals; }

	/* Rol: CarePlanTemplate o--> PatientProfileCare */
	private PatientProfileCareDTOA patient;
	public PatientProfileCareDTOA getPatient () { return patient; }
	public void setPatient (PatientProfileCareDTOA patient) { this.patient = patient; }

	/* Rol: CarePlanTemplate o--> Condition_CarePlan */
	private ArrayList<Condition_CarePlanDTOA> addressConditions;
	public ArrayList<Condition_CarePlanDTOA> getAddressConditions () { return addressConditions; }
	public void setAddressConditions (ArrayList<Condition_CarePlanDTOA> addressConditions) { this.addressConditions = addressConditions; }

	
	
	// endregion
	
	
	
	// region - Constructor and JSON <-> DTOA <-> DTO
	
	public CarePlanTemplateDTOA ()
	{
		// Empty constructor
	}
	
	@Override
	public void setFromJSON (JSONObject json)
	{
		try
		{
			if (!JSONObject.NULL.equals(json.opt("Id")))
			{
				this.id = (Integer) json.opt("Id");
			}
			

			if (!JSONObject.NULL.equals(json.opt("Status")))
			{
				int enumRawValue = (int) json.opt("Status");
				this.status = CareStatus.fromRawValue(enumRawValue);
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Intent")))
			{
				int enumRawValue = (int) json.opt("Intent");
				this.intent = CarePlanIntent.fromRawValue(enumRawValue);
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Title")))
			{
			 
				this.title = (String) json.opt("Title");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Modified")))
			{
			 
			 	String stringDate = (String) json.opt("Modified");
				this.modified = DateUtils.stringToDateFormat(stringDate);
			 
			}

			if (!JSONObject.NULL.equals(json.opt("DurationDays")))
			{
			 
				this.durationDays = (Integer) json.opt("DurationDays");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Name")))
			{
			 
				this.name = (String) json.opt("Name");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Description")))
			{
			 
				this.description = (String) json.opt("Description");
			 
			}
			

			JSONObject jsonCareActivities = json.optJSONObject("CareActivities");
			if (jsonCareActivities != null)
			{
				CareActivityDTOA tmp = new CareActivityDTOA();
				tmp.setFromJSON(jsonCareActivities);
				this.careActivities = tmp;
			}


			JSONObject jsonGoals = json.optJSONObject("Goals");
			if (jsonGoals != null)
			{
				GoalDTOA tmp = new GoalDTOA();
				tmp.setFromJSON(jsonGoals);
				this.goals = tmp;
			}


			JSONObject jsonPatient = json.optJSONObject("Patient");
			if (jsonPatient != null)
			{
				PatientProfileCareDTOA tmp = new PatientProfileCareDTOA();
				tmp.setFromJSON(jsonPatient);
				this.patient = tmp;
			}


			JSONObject jsonAddressConditions = json.optJSONObject("AddressConditions");
			if (jsonAddressConditions != null)
			{
				Condition_CarePlanDTOA tmp = new Condition_CarePlanDTOA();
				tmp.setFromJSON(jsonAddressConditions);
				this.addressConditions = tmp;
			}

			
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
	}
	
	public JSONObject toJSON ()
	{
		JSONObject json = new JSONObject();
		
		try
		{
			if (this.id != null){
				json.put("Id", this.id);
			}
			
		
		  if (this.status != null)
			json.put("Status", this.status.getRawValue());
		
		
		  if (this.intent != null)
			json.put("Intent", this.intent.getRawValue());
		
		
		  if (this.title != null)
			json.put("Title", this.title);
		
		
		  if (this.modified != null)
			json.put("Modified", DateUtils.dateToFormatString(this.modified));
		
		
		  if (this.durationDays != null)
			json.put("DurationDays", this.durationDays.intValue());
		
		
		  if (this.name != null)
			json.put("Name", this.name);
		
		
		  if (this.description != null)
			json.put("Description", this.description);
		
			

			if (this.careActivities != null)
			{
				json.put("CareActivities", this.careActivities.toJSON());
			}


			if (this.goals != null)
			{
				json.put("Goals", this.goals.toJSON());
			}


			if (this.patient != null)
			{
				json.put("Patient", this.patient.toJSON());
			}


			if (this.addressConditions != null)
			{
				json.put("AddressConditions", this.addressConditions.toJSON());
			}

			
		}
		catch (JSONException e)
		{
			e.printStackTrace();
		}
		
		return json;
	}
	
	@Override 
	public IDTO toDTO ()
	{
		CarePlanTemplateDTO dto = new CarePlanTemplateDTO ();
		
		// Attributes
		
	dto.setId (this.getId());

		
	dto.setStatus (this.getStatus());

	dto.setIntent (this.getIntent());

	dto.setTitle (this.getTitle());

	dto.setModified (this.getModified());

	dto.setDurationDays (this.getDurationDays());

	dto.setName (this.getName());

	dto.setDescription (this.getDescription());

		
		
		// Roles
					// TODO: from DTOA [ CareActivities ] (dataType : ArrayList<CareActivityDTOA>) to DTO [ CareActivity ]
					// TODO: from DTOA [ Goals ] (dataType : ArrayList<GoalDTOA>) to DTO [ Goals ]
					// TODO: from DTOA [ Patient ] (dataType : PatientProfileCareDTOA) to DTO [ PatientProfile ]
					// TODO: from DTOA [ AddressConditions ] (dataType : ArrayList<Condition_CarePlanDTOA>) to DTO [ AddressConditions ]
		
		
		return dto;
	}

	// endregion
}

	