
package MoSIoTGenMosIoTRESTAzure.uiModels.DTOA;

import MoSIoTGenMosIoTRESTAzure.uiModels.DTO.*;
import MoSIoTGenMosIoTRESTAzure.uiModels.DTO.utils.*;
import MoSIoTGenMosIoTRESTAzure.uiModels.DTO.enumerations.*;

import java.util.ArrayList;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Code autogenerated. Do not modify this file.
 */
public class CareActivityDTOA extends DTOA
{
	// region - Members, getters and setters

	private Integer id;
	public Integer getId () { return id; }
	public void setId (Integer id) { this.id = id; }

	
	private TypePeriodicity periodicity;
	public TypePeriodicity getPeriodicity () { return periodicity; }
	public void setPeriodicity (TypePeriodicity periodicity) { this.periodicity = periodicity; }
	
	private String description;
	public String getDescription () { return description; }
	public void setDescription (String description) { this.description = description; }
	
	private Integer duration;
	public Integer getDuration () { return duration; }
	public void setDuration (Integer duration) { this.duration = duration; }
	
	private String location;
	public String getLocation () { return location; }
	public void setLocation (String location) { this.location = location; }
	
	
	/* Rol: CareActivity o--> Medication */
	private MedicationDTOA medications;
	public MedicationDTOA getMedications () { return medications; }
	public void setMedications (MedicationDTOA medications) { this.medications = medications; }

	/* GetAll: Appointment */
	private ArrayList<AppointmentDTOA> appointments;
	public ArrayList<AppointmentDTOA> getAppointments () { return appointments; }
	public void setAppointments (ArrayList<AppointmentDTOA> appointments) { this.appointments = appointments; }

	/* Rol: CareActivity o--> NutritionOrder */
	private NutritionOrderDTOA nutritionOrders;
	public NutritionOrderDTOA getNutritionOrders () { return nutritionOrders; }
	public void setNutritionOrders (NutritionOrderDTOA nutritionOrders) { this.nutritionOrders = nutritionOrders; }

	
	
	// endregion
	
	
	
	// region - Constructor and JSON <-> DTOA <-> DTO
	
	public CareActivityDTOA ()
	{
		// Empty constructor
	}
	
	@Override
	public void setFromJSON (JSONObject json)
	{
		try
		{
			if (!JSONObject.NULL.equals(json.opt("Id")))
			{
				this.id = (Integer) json.opt("Id");
			}
			

			if (!JSONObject.NULL.equals(json.opt("Periodicity")))
			{
				int enumRawValue = (int) json.opt("Periodicity");
				this.periodicity = TypePeriodicity.fromRawValue(enumRawValue);
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Description")))
			{
			 
				this.description = (String) json.opt("Description");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Duration")))
			{
			 
				this.duration = (Integer) json.opt("Duration");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Location")))
			{
			 
				this.location = (String) json.opt("Location");
			 
			}
			

			JSONObject jsonMedications = json.optJSONObject("Medications");
			if (jsonMedications != null)
			{
				MedicationDTOA tmp = new MedicationDTOA();
				tmp.setFromJSON(jsonMedications);
				this.medications = tmp;
			}


			JSONArray arrayAppointments = json.optJSONArray("Appointments");
			if (arrayAppointments != null)
			{
				this.appointments = new ArrayList<AppointmentDTOA>();
				for (int i = 0; i < arrayAppointments.length(); ++i)
				{
					JSONObject subJson = (JSONObject) arrayAppointments.opt(i);
					AppointmentDTOA tmp = new AppointmentDTOA();
					tmp.setFromJSON(subJson);
					this.appointments.add(tmp);
				}
			}


			JSONObject jsonNutritionOrders = json.optJSONObject("NutritionOrders");
			if (jsonNutritionOrders != null)
			{
				NutritionOrderDTOA tmp = new NutritionOrderDTOA();
				tmp.setFromJSON(jsonNutritionOrders);
				this.nutritionOrders = tmp;
			}

			
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
	}
	
	public JSONObject toJSON ()
	{
		JSONObject json = new JSONObject();
		
		try
		{
			if (this.id != null){
				json.put("Id", this.id);
			}
			
		
		  if (this.periodicity != null)
			json.put("Periodicity", this.periodicity.getRawValue());
		
		
		  if (this.description != null)
			json.put("Description", this.description);
		
		
		  if (this.duration != null)
			json.put("Duration", this.duration.intValue());
		
		
		  if (this.location != null)
			json.put("Location", this.location);
		
			

			if (this.medications != null)
			{
				json.put("Medications", this.medications.toJSON());
			}


			if (this.appointments != null)
			{
				JSONArray jsonArray = new JSONArray();
				for (int i = 0; i < this.appointments.size(); ++i)
				{
					jsonArray.put(this.appointments.get(i).toJSON());
				}
				json.put("Appointments", jsonArray);
			}


			if (this.nutritionOrders != null)
			{
				json.put("NutritionOrders", this.nutritionOrders.toJSON());
			}

			
		}
		catch (JSONException e)
		{
			e.printStackTrace();
		}
		
		return json;
	}
	
	@Override 
	public IDTO toDTO ()
	{
		CareActivityDTO dto = new CareActivityDTO ();
		
		// Attributes
		
	dto.setId (this.getId());

		
	dto.setPeriodicity (this.getPeriodicity());

	dto.setDescription (this.getDescription());

	dto.setDuration (this.getDuration());

	dto.setLocation (this.getLocation());

		
		
		// Roles
					// TODO: from DTOA [ Medications ] (dataType : MedicationDTOA) to DTO [ Medication ]
					// TODO: from DTOA [ NutritionOrders ] (dataType : NutritionOrderDTOA) to DTO [ NutritionOrder ]
		
		
		return dto;
	}

	// endregion
}

	