
package MoSIoTGenMosIoTRESTAzure.uiModels.DTOA;

import MoSIoTGenMosIoTRESTAzure.uiModels.DTO.*;
import MoSIoTGenMosIoTRESTAzure.uiModels.DTO.utils.*;
import MoSIoTGenMosIoTRESTAzure.uiModels.DTO.enumerations.*;

import java.util.ArrayList;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Code autogenerated. Do not modify this file.
 */
public class MeasureDTOA extends DTOA
{
	// region - Members, getters and setters

	private Integer id;
	public Integer getId () { return id; }
	public void setId (Integer id) { this.id = id; }

	
	private String name;
	public String getName () { return name; }
	public void setName (String name) { this.name = name; }
	
	private String description;
	public String getDescription () { return description; }
	public void setDescription (String description) { this.description = description; }
	
	private String lOINCcode;
	public String getLOINCcode () { return lOINCcode; }
	public void setLOINCcode (String lOINCcode) { this.lOINCcode = lOINCcode; }
	
	
	/* Rol: Measure o--> Telemetry_2 */
	private ArrayList<Telemetry_2DTOA> telemetriesMeasure;
	public ArrayList<Telemetry_2DTOA> getTelemetriesMeasure () { return telemetriesMeasure; }
	public void setTelemetriesMeasure (ArrayList<Telemetry_2DTOA> telemetriesMeasure) { this.telemetriesMeasure = telemetriesMeasure; }

	
	
	// endregion
	
	
	
	// region - Constructor and JSON <-> DTOA <-> DTO
	
	public MeasureDTOA ()
	{
		// Empty constructor
	}
	
	@Override
	public void setFromJSON (JSONObject json)
	{
		try
		{
			if (!JSONObject.NULL.equals(json.opt("Id")))
			{
				this.id = (Integer) json.opt("Id");
			}
			

			if (!JSONObject.NULL.equals(json.opt("Name")))
			{
			 
				this.name = (String) json.opt("Name");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Description")))
			{
			 
				this.description = (String) json.opt("Description");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("LOINCcode")))
			{
			 
				this.lOINCcode = (String) json.opt("LOINCcode");
			 
			}
			

			JSONObject jsonTelemetriesMeasure = json.optJSONObject("TelemetriesMeasure");
			if (jsonTelemetriesMeasure != null)
			{
				Telemetry_2DTOA tmp = new Telemetry_2DTOA();
				tmp.setFromJSON(jsonTelemetriesMeasure);
				this.telemetriesMeasure = tmp;
			}

			
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
	}
	
	public JSONObject toJSON ()
	{
		JSONObject json = new JSONObject();
		
		try
		{
			if (this.id != null){
				json.put("Id", this.id);
			}
			
		
		  if (this.name != null)
			json.put("Name", this.name);
		
		
		  if (this.description != null)
			json.put("Description", this.description);
		
		
		  if (this.lOINCcode != null)
			json.put("LOINCcode", this.lOINCcode);
		
			

			if (this.telemetriesMeasure != null)
			{
				json.put("TelemetriesMeasure", this.telemetriesMeasure.toJSON());
			}

			
		}
		catch (JSONException e)
		{
			e.printStackTrace();
		}
		
		return json;
	}
	
	@Override 
	public IDTO toDTO ()
	{
		MeasureDTO dto = new MeasureDTO ();
		
		// Attributes
		
	dto.setId (this.getId());

		
	dto.setName (this.getName());

	dto.setDescription (this.getDescription());

	dto.setLOINCcode (this.getLOINCcode());

		
		
		// Roles
					// TODO: from DTOA [ TelemetriesMeasure ] (dataType : ArrayList<Telemetry_2DTOA>) to DTO [ Telemetry ]
		
		
		return dto;
	}

	// endregion
}

	