//
// AdaptationRequestDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class AdaptationRequestDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	var accessModeTarget: AccessModeValue?;
	var languageOfAdaptation: LanguageCode?;
	var description: String?;
	
	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
		if let enumValue = json["AccessModeTarget"].object as? Int
		{
			self.accessModeTarget = AccessModeValue(rawValue: enumValue);
		}
		if let enumValue = json["LanguageOfAdaptation"].object as? Int
		{
			self.languageOfAdaptation = LanguageCode(rawValue: enumValue);
		}
		self.description = json["Description"].object as? String;
		
		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	

	
		dictionary["AccessModeTarget"] = self.accessModeTarget?.rawValue;
	
	

	
		dictionary["LanguageOfAdaptation"] = self.languageOfAdaptation?.rawValue;
	
	

	
		dictionary["Description"] = self.description;
	
	
		
		
		
		return dictionary;
	}
}

	