//
// CarePlanTemplateDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class CarePlanTemplateDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	var status: CareStatus?;
	var intent: CarePlanInent?;
	var title: String?;
	var modified: NSDate?;
	
	/* Rol: CarePlanTemplate o--> CareActivity */
	var careActivities: [CareActivityDTOA]?;

	/* Rol: CarePlanTemplate o--> Goal */
	var goals: [GoalDTOA]?;

	/* Rol: CarePlanTemplate o--> PatientProfileCare */
	var patient: PatientProfileCareDTOA?;

	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
		if let enumValue = json["Status"].object as? Int
		{
			self.status = CareStatus(rawValue: enumValue);
		}
		if let enumValue = json["Intent"].object as? Int
		{
			self.intent = CarePlanInent(rawValue: enumValue);
		}
		self.title = json["Title"].object as? String;
	
		self.modified = NSDate.initFromString(json["Modified"].object as? String);
		
		if (json["CareActivities"] != JSON.null)
		{
			self.careActivities = CareActivityDTOA(fromJSONObject: json["CareActivities"]);
		}

		if (json["Goals"] != JSON.null)
		{
			self.goals = GoalDTOA(fromJSONObject: json["Goals"]);
		}

		if (json["Patient"] != JSON.null)
		{
			self.patient = PatientProfileCareDTOA(fromJSONObject: json["Patient"]);
		}

		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	

	
		dictionary["Status"] = self.status?.rawValue;
	
	

	
		dictionary["Intent"] = self.intent?.rawValue;
	
	

	
		dictionary["Title"] = self.title;
	
	

	
		dictionary["Modified"] = self.modified?.toString();
	
	
		
		dictionary["CareActivities"] = self.careActivities?.toDictionary() ?? NSNull();

		dictionary["Goals"] = self.goals?.toDictionary() ?? NSNull();

		dictionary["Patient"] = self.patient?.toDictionary() ?? NSNull();

		
		
		return dictionary;
	}
}

	