//
// LocationTelemetryDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class LocationTelemetryDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	var latitude: Int?;
	var longitude: Int?;
	var altitude: Int?;
	
	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
		self.latitude = json["Latitude"].object as? Int;
		self.longitude = json["Longitude"].object as? Int;
		self.altitude = json["Altitude"].object as? Int;
		
		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	

	
		dictionary["Latitude"] = self.latitude;
	
	

	
		dictionary["Longitude"] = self.longitude;
	
	

	
		dictionary["Altitude"] = self.altitude;
	
	
		
		
		
		return dictionary;
	}
}

	