//
// PatientProfileCareDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class PatientProfileCareDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	var preferredLanguage: LanguageCode?;
	var region: String?;
	var hazardAvoidance: HazardValue?;
	
	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
		if let enumValue = json["PreferredLanguage"].object as? Int
		{
			self.preferredLanguage = LanguageCode(rawValue: enumValue);
		}
		self.region = json["Region"].object as? String;
		if let enumValue = json["HazardAvoidance"].object as? Int
		{
			self.hazardAvoidance = HazardValue(rawValue: enumValue);
		}
		
		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	

	
		dictionary["PreferredLanguage"] = self.preferredLanguage?.rawValue;
	
	

	
		dictionary["Region"] = self.region;
	
	

	
		dictionary["HazardAvoidance"] = self.hazardAvoidance?.rawValue;
	
	
		
		
		
		return dictionary;
	}
}

	