//
// StateTelemetryDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class StateTelemetryDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	
	/* Rol: StateTelemetry o--> StateDevice */
	var states: [StateDeviceDTOA]?;

	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
		
		if (json["States"] != JSON.null)
		{
			self.states = StateDeviceDTOA(fromJSONObject: json["States"]);
		}

		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	
		
		dictionary["States"] = self.states?.toDictionary() ?? NSNull();

		
		
		return dictionary;
	}
}

	