	
		package MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.utils.*;
		import  MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class AdaptationRequestDTO 	    implements IDTO
	    {
				private AccessModeValue accessModeTarget;
				public AccessModeValue getAccessModeTarget () { return accessModeTarget; } 
				public void setAccessModeTarget  (AccessModeValue value) { accessModeTarget = value;  } 
				    	 
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private Integer accessMode_oid;
				public Integer  getAccessMode_oid () { return accessMode_oid; } 
				public void setAccessMode_oid (Integer value) { accessMode_oid = value;  } 
				    	 
				private LanguageCode languageOfAdaptation;
				public LanguageCode getLanguageOfAdaptation () { return languageOfAdaptation; } 
				public void setLanguageOfAdaptation  (LanguageCode value) { languageOfAdaptation = value;  } 
				    	 
				private String description;
				public String getDescription () { return description; } 
				public void setDescription  (String value) { description = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("AccessModeTarget", this.accessModeTarget.getRawValue());
				
				
						  json.put("Id", this.id.intValue());
				

						if (this.accessMode_oid != null)
						{
							json.put("AccessMode_oid", this.accessMode_oid.intValue());
						}
				
						  json.put("LanguageOfAdaptation", this.languageOfAdaptation.getRawValue());
				
				
						  json.put("Description", this.description);
				
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	