	
		package MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.utils.*;
		import  MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class DeviceTemplateDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private String name;
				public String getName () { return name; } 
				public void setName  (String value) { name = value;  } 
				    	 
				private ArrayList<PropertyDTO> property;
				public ArrayList<PropertyDTO> getProperty () { return property; } 
				public void setProperty (ArrayList<PropertyDTO> value) { property = value;  } 
				    	 
				private ArrayList<CommandDTO> command;
				public ArrayList<CommandDTO> getCommand () { return command; } 
				public void setCommand (ArrayList<CommandDTO> value) { command = value;  } 
				    	 
				private ArrayList<TelemetryDTO> telemetry;
				public ArrayList<TelemetryDTO> getTelemetry () { return telemetry; } 
				public void setTelemetry (ArrayList<TelemetryDTO> value) { telemetry = value;  } 
				    	 
				private DeviceType type;
				public DeviceType getType () { return type; } 
				public void setType  (DeviceType value) { type = value;  } 
				    	 
				private Boolean isEdge;
				public Boolean getIsEdge () { return isEdge; } 
				public void setIsEdge  (Boolean value) { isEdge = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				
				
						  json.put("Name", this.name);
				

						if (this.property != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.property.size(); ++i)
							{
								jsonArray.put(this.property.get(i).toJSON());
							}
							json.put("Property", jsonArray);
						}

						if (this.command != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.command.size(); ++i)
							{
								jsonArray.put(this.command.get(i).toJSON());
							}
							json.put("Command", jsonArray);
						}

						if (this.telemetry != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.telemetry.size(); ++i)
							{
								jsonArray.put(this.telemetry.get(i).toJSON());
							}
							json.put("Telemetry", jsonArray);
						}
				
						  json.put("Type", this.type.getRawValue());
				
				
						  json.put("IsEdge", this.isEdge);
				
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	