	
		package MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.utils.*;
		import  MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class EntityDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private String name;
				public String getName () { return name; } 
				public void setName  (String value) { name = value;  } 
				    	 
				private ArrayList<Integer> originAssociation_oid;
				public ArrayList<Integer>  getOriginAssociation_oid () { return originAssociation_oid; } 
				public void setOriginAssociation_oid (ArrayList<Integer> value) { originAssociation_oid = value;  } 
				    	 
				private ArrayList<Integer> targetAssociation_oid;
				public ArrayList<Integer>  getTargetAssociation_oid () { return targetAssociation_oid; } 
				public void setTargetAssociation_oid (ArrayList<Integer> value) { targetAssociation_oid = value;  } 
				    	 
				private Integer scenario_oid;
				public Integer  getScenario_oid () { return scenario_oid; } 
				public void setScenario_oid (Integer value) { scenario_oid = value;  } 
				    	 
				private String description;
				public String getDescription () { return description; } 
				public void setDescription  (String value) { description = value;  } 
				    	 
				private ArrayList<EntityOperationDTO> operations;
				public ArrayList<EntityOperationDTO> getOperations () { return operations; } 
				public void setOperations (ArrayList<EntityOperationDTO> value) { operations = value;  } 
				    	 
				private ArrayList<EntityAttributesDTO> attributes;
				public ArrayList<EntityAttributesDTO> getAttributes () { return attributes; } 
				public void setAttributes (ArrayList<EntityAttributesDTO> value) { attributes = value;  } 
				    	 
				private ArrayList<EntityStateDTO> states;
				public ArrayList<EntityStateDTO> getStates () { return states; } 
				public void setStates (ArrayList<EntityStateDTO> value) { states = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				
				
						  json.put("Name", this.name);
				

						if (this.originAssociation_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.originAssociation_oid.size(); ++i)
							{
								jsonArray.put(this.originAssociation_oid.get(i));
							}
							json.put("OriginAssociation_oid", jsonArray);
						}
		

						if (this.targetAssociation_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.targetAssociation_oid.size(); ++i)
							{
								jsonArray.put(this.targetAssociation_oid.get(i));
							}
							json.put("TargetAssociation_oid", jsonArray);
						}
		

						if (this.scenario_oid != null)
						{
							json.put("Scenario_oid", this.scenario_oid.intValue());
						}
				
						  json.put("Description", this.description);
				

						if (this.operations != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.operations.size(); ++i)
							{
								jsonArray.put(this.operations.get(i).toJSON());
							}
							json.put("Operations", jsonArray);
						}

						if (this.attributes != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.attributes.size(); ++i)
							{
								jsonArray.put(this.attributes.get(i).toJSON());
							}
							json.put("Attributes", jsonArray);
						}

						if (this.states != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.states.size(); ++i)
							{
								jsonArray.put(this.states.get(i).toJSON());
							}
							json.put("States", jsonArray);
						}
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	