	
		package MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.utils.*;
		import  MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class EventTelemetryDTO extends    		SpecificTelemetryDTO
	    implements IDTO
	    {
				private SeverityEvent severity;
				public SeverityEvent getSeverity () { return severity; } 
				public void setSeverity  (SeverityEvent value) { severity = value;  } 
				    	 
				private Integer eventCommand_oid;
				public Integer  getEventCommand_oid () { return eventCommand_oid; } 
				public void setEventCommand_oid (Integer value) { eventCommand_oid = value;  } 
				    	 
				private Integer notification_oid;
				public Integer  getNotification_oid () { return notification_oid; } 
				public void setNotification_oid (Integer value) { notification_oid = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Severity", this.severity.getRawValue());
				

						if (this.eventCommand_oid != null)
						{
							json.put("EventCommand_oid", this.eventCommand_oid.intValue());
						}

						if (this.notification_oid != null)
						{
							json.put("Notification_oid", this.notification_oid.intValue());
						}
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	