	
		package MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.utils.*;
		import  MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class GoalDTO 	    implements IDTO
	    {
				private Integer carePlanTemplate_oid;
				public Integer  getCarePlanTemplate_oid () { return carePlanTemplate_oid; } 
				public void setCarePlanTemplate_oid (Integer value) { carePlanTemplate_oid = value;  } 
				    	 
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private PriorityType priority;
				public PriorityType getPriority () { return priority; } 
				public void setPriority  (PriorityType value) { priority = value;  } 
				    	 
				private ArrayList<TargetDTO> targets;
				public ArrayList<TargetDTO> getTargets () { return targets; } 
				public void setTargets (ArrayList<TargetDTO> value) { targets = value;  } 
				    	 
				private CareStatus status;
				public CareStatus getStatus () { return status; } 
				public void setStatus  (CareStatus value) { status = value;  } 
				    	 
				private Integer condition_oid;
				public Integer  getCondition_oid () { return condition_oid; } 
				public void setCondition_oid (Integer value) { condition_oid = value;  } 
				    	 
				private String description;
				public String getDescription () { return description; } 
				public void setDescription  (String value) { description = value;  } 
				    	 
				private CategoryGoal category;
				public CategoryGoal getCategory () { return category; } 
				public void setCategory  (CategoryGoal value) { category = value;  } 
				    	 
				private String outcomeCode;
				public String getOutcomeCode () { return outcomeCode; } 
				public void setOutcomeCode  (String value) { outcomeCode = value;  } 
				    	 
				private String name;
				public String getName () { return name; } 
				public void setName  (String value) { name = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{

						if (this.carePlanTemplate_oid != null)
						{
							json.put("CarePlanTemplate_oid", this.carePlanTemplate_oid.intValue());
						}
				
						  json.put("Id", this.id.intValue());
				
				
						  json.put("Priority", this.priority.getRawValue());
				

						if (this.targets != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.targets.size(); ++i)
							{
								jsonArray.put(this.targets.get(i).toJSON());
							}
							json.put("Targets", jsonArray);
						}
				
						  json.put("Status", this.status.getRawValue());
				

						if (this.condition_oid != null)
						{
							json.put("Condition_oid", this.condition_oid.intValue());
						}
				
						  json.put("Description", this.description);
				
				
						  json.put("Category", this.category.getRawValue());
				
				
						  json.put("OutcomeCode", this.outcomeCode);
				
				
						  json.put("Name", this.name);
				
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	