	
		package MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.utils.*;
		import  MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class IMAppointmentDTO extends    		EntityDTO
	    implements IDTO
	    {
				private java.util.Date date;
				public java.util.Date getDate () { return date; } 
				public void setDate  (java.util.Date value) { date = value;  } 
				    	 
				private Integer appointment_oid;
				public Integer  getAppointment_oid () { return appointment_oid; } 
				public void setAppointment_oid (Integer value) { appointment_oid = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Date", DateUtils.dateToFormatString(this.date));
				

						if (this.appointment_oid != null)
						{
							json.put("Appointment_oid", this.appointment_oid.intValue());
						}
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	