	
		package MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.utils.*;
		import  MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class IMTelemetryValuesDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private java.util.Date timeStamp;
				public java.util.Date getTimeStamp () { return timeStamp; } 
				public void setTimeStamp  (java.util.Date value) { timeStamp = value;  } 
				    	 
				private String valu;
				public String getValu () { return valu; } 
				public void setValu  (String value) { valu = value;  } 
				    	 
				private Integer iMTelemetry_oid;
				public Integer  getIMTelemetry_oid () { return iMTelemetry_oid; } 
				public void setIMTelemetry_oid (Integer value) { iMTelemetry_oid = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				
				
						  json.put("TimeStamp", DateUtils.dateToFormatString(this.timeStamp));
				
				
						  json.put("Valu", this.valu);
				

						if (this.iMTelemetry_oid != null)
						{
							json.put("IMTelemetry_oid", this.iMTelemetry_oid.intValue());
						}
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	