	
		package MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.utils.*;
		import  MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class MeasureDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private String name;
				public String getName () { return name; } 
				public void setName  (String value) { name = value;  } 
				    	 
				private String description;
				public String getDescription () { return description; } 
				public void setDescription  (String value) { description = value;  } 
				    	 
				private ArrayList<Integer> target_oid;
				public ArrayList<Integer>  getTarget_oid () { return target_oid; } 
				public void setTarget_oid (ArrayList<Integer> value) { target_oid = value;  } 
				    	 
				private ArrayList<Integer> telemetry_oid;
				public ArrayList<Integer>  getTelemetry_oid () { return telemetry_oid; } 
				public void setTelemetry_oid (ArrayList<Integer> value) { telemetry_oid = value;  } 
				    	 
				private String lOINCcode;
				public String getLOINCcode () { return lOINCcode; } 
				public void setLOINCcode  (String value) { lOINCcode = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				
				
						  json.put("Name", this.name);
				
				
						  json.put("Description", this.description);
				

						if (this.target_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.target_oid.size(); ++i)
							{
								jsonArray.put(this.target_oid.get(i));
							}
							json.put("Target_oid", jsonArray);
						}
		

						if (this.telemetry_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.telemetry_oid.size(); ++i)
							{
								jsonArray.put(this.telemetry_oid.get(i));
							}
							json.put("Telemetry_oid", jsonArray);
						}
		
				
						  json.put("LOINCcode", this.lOINCcode);
				
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	