	
		package MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.utils.*;
		import  MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class PropertyDTO 	    implements IDTO
	    {
				private Integer deviceTemplate_oid;
				public Integer  getDeviceTemplate_oid () { return deviceTemplate_oid; } 
				public void setDeviceTemplate_oid (Integer value) { deviceTemplate_oid = value;  } 
				    	 
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private String name;
				public String getName () { return name; } 
				public void setName  (String value) { name = value;  } 
				    	 
				private Boolean isWritable;
				public Boolean getIsWritable () { return isWritable; } 
				public void setIsWritable  (Boolean value) { isWritable = value;  } 
				    	 
				private Boolean isCloudable;
				public Boolean getIsCloudable () { return isCloudable; } 
				public void setIsCloudable  (Boolean value) { isCloudable = value;  } 
				    	 
				private ArrayList<Integer> telemetry_oid;
				public ArrayList<Integer>  getTelemetry_oid () { return telemetry_oid; } 
				public void setTelemetry_oid (ArrayList<Integer> value) { telemetry_oid = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{

						if (this.deviceTemplate_oid != null)
						{
							json.put("DeviceTemplate_oid", this.deviceTemplate_oid.intValue());
						}
				
						  json.put("Id", this.id.intValue());
				
				
						  json.put("Name", this.name);
				
				
						  json.put("IsWritable", this.isWritable);
				
				
						  json.put("IsCloudable", this.isCloudable);
				

						if (this.telemetry_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.telemetry_oid.size(); ++i)
							{
								jsonArray.put(this.telemetry_oid.get(i));
							}
							json.put("Telemetry_oid", jsonArray);
						}
		
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	