	
		package MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.utils.*;
		import  MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class RecipeDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private String name;
				public String getName () { return name; } 
				public void setName  (String value) { name = value;  } 
				    	 
				private Boolean isEnabled;
				public Boolean getIsEnabled () { return isEnabled; } 
				public void setIsEnabled  (Boolean value) { isEnabled = value;  } 
				    	 
				private RecipeTriggerDTO triggers;
				public RecipeTriggerDTO getTriggers () { return triggers; } 
				public void setTriggers (RecipeTriggerDTO value) { triggers = value;  } 
				    	 
				private ArrayList<RecipeActionDTO> recipeAction;
				public ArrayList<RecipeActionDTO> getRecipeAction () { return recipeAction; } 
				public void setRecipeAction (ArrayList<RecipeActionDTO> value) { recipeAction = value;  } 
				    	 
				private Integer ioTScenario_oid;
				public Integer  getIoTScenario_oid () { return ioTScenario_oid; } 
				public void setIoTScenario_oid (Integer value) { ioTScenario_oid = value;  } 
				    	 
				private Double intervalTime;
				public Double getIntervalTime () { return intervalTime; } 
				public void setIntervalTime  (Double value) { intervalTime = value;  } 
				    	 
				private String description;
				public String getDescription () { return description; } 
				public void setDescription  (String value) { description = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				
				
						  json.put("Name", this.name);
				
				
						  json.put("IsEnabled", this.isEnabled);
				

						if (this.triggers != null)
						{
							json.put("Triggers", this.triggers.toJSON());
						}

						if (this.recipeAction != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.recipeAction.size(); ++i)
							{
								jsonArray.put(this.recipeAction.get(i).toJSON());
							}
							json.put("RecipeAction", jsonArray);
						}

						if (this.ioTScenario_oid != null)
						{
							json.put("IoTScenario_oid", this.ioTScenario_oid.intValue());
						}
				
						  json.put("IntervalTime", this.intervalTime);
				
				
						  json.put("Description", this.description);
				
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	