	
		package MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.utils.*;
		import  MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class RelatedPersonDTO extends    		EntityDTO
	    implements IDTO
	    {
				private Integer userRelatedPerson_oid;
				public Integer  getUserRelatedPerson_oid () { return userRelatedPerson_oid; } 
				public void setUserRelatedPerson_oid (Integer value) { userRelatedPerson_oid = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{

						if (this.userRelatedPerson_oid != null)
						{
							json.put("UserRelatedPerson_oid", this.userRelatedPerson_oid.intValue());
						}
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	