
using System;

namespace MoSIoTGenNHibernate.Enumerated.MosIoT
{
public enum DataTypeEnum { Autogenerated=1, Enum=2, Integer=3, String=4, Double=5, Boolean=6, Text=7, Long=8, Time=9, Date=10, Object=11, OID=12 };
}
