	
		//
		// AccessModeDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class AccessModeDTO 	    {
		 
				var patient_oid: Int?;
				    	 
		 
				var id: Int?;
				    	 
		 
				var typeAccessMode: AccessModeValue?;
				    	 
		 
				var adaptationDetailRequired: [AdaptationDetailRequiredDTO]?;
				    	 
		 
				var deviceTemplate_oid: [Int]?;
				    	 
		 
				var description: String?;
				    	 
		 
				var adaptationTypeRequired: [AdaptationTypeRequiredDTO]?;
				    	 
		 
				var adaptationRequest: [AdaptationRequestDTO]?;
				    	 
		 
				var disability_oid: Int?;
				    	 
		 
				var name: String?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


					dictionary["patient_oid"] = self.patient_oid;
			

				
					dictionary["id"] = self.id;
				

				
					dictionary["typeAccessMode"] = self.typeAccessMode?.rawValue;
				

					dictionary["adaptationDetailRequired"] = NSNull();
					if (self.adaptationDetailRequired != nil)
					{
						var arrayOfDictionary: [[String : AnyObject]] = [];
						for item in self.adaptationDetailRequired!
						{
							arrayOfDictionary.append(item.toDictionary());
						}
						
						dictionary["adaptationDetailRequired"] = arrayOfDictionary;
					}
			

					dictionary["deviceTemplate_oid"] = self.deviceTemplate_oid;
			

				
					dictionary["description"] = self.description;
				

					dictionary["adaptationTypeRequired"] = NSNull();
					if (self.adaptationTypeRequired != nil)
					{
						var arrayOfDictionary: [[String : AnyObject]] = [];
						for item in self.adaptationTypeRequired!
						{
							arrayOfDictionary.append(item.toDictionary());
						}
						
						dictionary["adaptationTypeRequired"] = arrayOfDictionary;
					}
			

					dictionary["adaptationRequest"] = NSNull();
					if (self.adaptationRequest != nil)
					{
						var arrayOfDictionary: [[String : AnyObject]] = [];
						for item in self.adaptationRequest!
						{
							arrayOfDictionary.append(item.toDictionary());
						}
						
						dictionary["adaptationRequest"] = arrayOfDictionary;
					}
			

					dictionary["disability_oid"] = self.disability_oid;
			

				
					dictionary["name"] = self.name;
				
						
				return dictionary;
			}
		}
		
	