	
		//
		// AppointmentDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class AppointmentDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var isVirtual: Bool?;
				    	 
		 
				var description: String?;
				    	 
		 
				var direction: String?;
				    	 
		 
				var reasonCode: String?;
				    	 
		 
				var careActivity_oid: Int?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

				
					dictionary["isVirtual"] = self.isVirtual;
				

				
					dictionary["description"] = self.description;
				

				
					dictionary["direction"] = self.direction;
				

				
					dictionary["reasonCode"] = self.reasonCode;
				

					dictionary["careActivity_oid"] = self.careActivity_oid;
			
						
				return dictionary;
			}
		}
		
	