	
		//
		// CommandDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class CommandDTO 	    {
		 
				var deviceTemplate_oid: Int?;
				    	 
		 
				var id: Int?;
				    	 
		 
				var name: String?;
				    	 
		 
				var isSynchronous: Bool?;
				    	 
		 
				var telemetries_oid: [Int]?;
				    	 
		 
				var type: OperationType?;
				    	 
		 
				var description: String?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


					dictionary["deviceTemplate_oid"] = self.deviceTemplate_oid;
			

				
					dictionary["id"] = self.id;
				

				
					dictionary["name"] = self.name;
				

				
					dictionary["isSynchronous"] = self.isSynchronous;
				

					dictionary["telemetries_oid"] = self.telemetries_oid;
			

				
					dictionary["type"] = self.type?.rawValue;
				

				
					dictionary["description"] = self.description;
				
						
				return dictionary;
			}
		}
		
	