	
		//
		// DisabilityDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class DisabilityDTO 	    {
		 
				var patient_oid: Int?;
				    	 
		 
				var id: Int?;
				    	 
		 
				var name: String?;
				    	 
		 
				var type: DisabilityType?;
				    	 
		 
				var severity: Severity?;
				    	 
		 
				var origin_oid: Int?;
				    	 
		 
				var accessMode_oid: [Int]?;
				    	 
		 
				var description: String?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


					dictionary["patient_oid"] = self.patient_oid;
			

				
					dictionary["id"] = self.id;
				

				
					dictionary["name"] = self.name;
				

				
					dictionary["type"] = self.type?.rawValue;
				

				
					dictionary["severity"] = self.severity?.rawValue;
				

					dictionary["origin_oid"] = self.origin_oid;
			

					dictionary["accessMode_oid"] = self.accessMode_oid;
			

				
					dictionary["description"] = self.description;
				
						
				return dictionary;
			}
		}
		
	