	
		//
		// EntityAttributesDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class EntityAttributesDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var name: String?;
				    	 
		 
				var type: DataType?;
				    	 
		 
				var isOID: Bool?;
				    	 
		 
				var targetAssociation_oid: [Int]?;
				    	 
		 
				var originAsociation_oid: [Int]?;
				    	 
		 
				var associationType: AssociationType?;
				    	 
		 
				var isWritable: Bool?;
				    	 
		 
				var description: String?;
				    	 
		 
				var entity_oid: Int?;
				    	 
		 
				var trigger_oid: [Int]?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

				
					dictionary["name"] = self.name;
				

				
					dictionary["type"] = self.type?.rawValue;
				

				
					dictionary["isOID"] = self.isOID;
				

					dictionary["targetAssociation_oid"] = self.targetAssociation_oid;
			

					dictionary["originAsociation_oid"] = self.originAsociation_oid;
			

				
					dictionary["associationType"] = self.associationType?.rawValue;
				

				
					dictionary["isWritable"] = self.isWritable;
				

				
					dictionary["description"] = self.description;
				

					dictionary["entity_oid"] = self.entity_oid;
			

					dictionary["trigger_oid"] = self.trigger_oid;
			
						
				return dictionary;
			}
		}
		
	