	
		//
		// HealthDataDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class HealthDataDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var description: String?;
				    	 
		 
				var language: LanguageCode?;
				    	 
		 
				var system: String?;
				    	 
		 
				var code: String?;
				    	 
		 
				var display: String?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

				
					dictionary["description"] = self.description;
				

				
					dictionary["language"] = self.language?.rawValue;
				

				
					dictionary["system"] = self.system;
				

				
					dictionary["code"] = self.code;
				

				
					dictionary["display"] = self.display;
				
						
				return dictionary;
			}
		}
		
	