	
		//
		// IMAppointmentDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class IMAppointmentDTO :    		EntityAttributesDTO
	    {
		 
				var date: NSDate?;
				    	 
		 
				var appointment_oid: Int?;
				    	 
	   	   
			// MARK: - Constructor
			
			
			override init ()
			{
				super.init();
			}
			override func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
				dictionary = super.toDictionary();
			


				
					dictionary["date"] = self.date?.toString();
				

					dictionary["appointment_oid"] = self.appointment_oid;
			
						
				return dictionary;
			}
		}
		
	