	
		//
		// IMPropertyDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class IMPropertyDTO :    		EntityAttributesDTO
	    {
		 
				var property_oid: Int?;
				    	 
	   	   
			// MARK: - Constructor
			
			
			override init ()
			{
				super.init();
			}
			override func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
				dictionary = super.toDictionary();
			


					dictionary["property_oid"] = self.property_oid;
			
						
				return dictionary;
			}
		}
		
	