	
		//
		// InheritanceDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class InheritanceDTO 	    {
		 
				var father_oid: [Int]?;
				    	 
		 
				var son_oid: Int?;
				    	 
		 
				var id: Int?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


					dictionary["father_oid"] = self.father_oid;
			

					dictionary["son_oid"] = self.son_oid;
			

				
					dictionary["id"] = self.id;
				
						
				return dictionary;
			}
		}
		
	