	
		//
		// LocationTelemetryDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class LocationTelemetryDTO :    		SpecificTelemetryDTO
	    {
		 
				var latitude: Int?;
				    	 
		 
				var longitude: Int?;
				    	 
		 
				var altitude: Int?;
				    	 
	   	   
			// MARK: - Constructor
			
			
			override init ()
			{
				super.init();
			}
			override func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
				dictionary = super.toDictionary();
			


				
					dictionary["latitude"] = self.latitude;
				

				
					dictionary["longitude"] = self.longitude;
				

				
					dictionary["altitude"] = self.altitude;
				
						
				return dictionary;
			}
		}
		
	