	
		//
		// MeasureDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class MeasureDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var name: String?;
				    	 
		 
				var description: String?;
				    	 
		 
				var target_oid: [Int]?;
				    	 
		 
				var telemetry_oid: [Int]?;
				    	 
		 
				var lOINCcode: String?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

				
					dictionary["name"] = self.name;
				

				
					dictionary["description"] = self.description;
				

					dictionary["target_oid"] = self.target_oid;
			

					dictionary["telemetry_oid"] = self.telemetry_oid;
			

				
					dictionary["lOINCcode"] = self.lOINCcode;
				
						
				return dictionary;
			}
		}
		
	