	
		//
		// NotificationUserDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class NotificationUserDTO 	    {
		 
				var notification_oid: Int?;
				    	 
		 
				var id: Int?;
				    	 
		 
				var user_oid: String?;
				    	 
		 
				var isReceived: Bool?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


					dictionary["notification_oid"] = self.notification_oid;
			

				
					dictionary["id"] = self.id;
				

					dictionary["user_oid"] = self.user_oid;
			

				
					dictionary["isReceived"] = self.isReceived;
				
						
				return dictionary;
			}
		}
		
	