	
		//
		// RuleActionDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class RuleActionDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var rule_oid: Int?;
				    	 
		 
				var operation_oid: Int?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

					dictionary["rule_oid"] = self.rule_oid;
			

					dictionary["operation_oid"] = self.operation_oid;
			
						
				return dictionary;
			}
		}
		
	