	
		//
		// RuleDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class RuleDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var name: String?;
				    	 
		 
				var isEnabled: Bool?;
				    	 
		 
				var condition: [RuleConditionDTO]?;
				    	 
		 
				var ruleAction: [RuleActionDTO]?;
				    	 
		 
				var ioTScenario_oid: Int?;
				    	 
		 
				var intervalTime: Double?;
				    	 
		 
				var description: String?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

				
					dictionary["name"] = self.name;
				

				
					dictionary["isEnabled"] = self.isEnabled;
				

					dictionary["condition"] = NSNull();
					if (self.condition != nil)
					{
						var arrayOfDictionary: [[String : AnyObject]] = [];
						for item in self.condition!
						{
							arrayOfDictionary.append(item.toDictionary());
						}
						
						dictionary["condition"] = arrayOfDictionary;
					}
			

					dictionary["ruleAction"] = NSNull();
					if (self.ruleAction != nil)
					{
						var arrayOfDictionary: [[String : AnyObject]] = [];
						for item in self.ruleAction!
						{
							arrayOfDictionary.append(item.toDictionary());
						}
						
						dictionary["ruleAction"] = arrayOfDictionary;
					}
			

					dictionary["ioTScenario_oid"] = self.ioTScenario_oid;
			

				
					dictionary["intervalTime"] = self.intervalTime;
				

				
					dictionary["description"] = self.description;
				
						
				return dictionary;
			}
		}
		
	