	
		//
		// SpecificTelemetryDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class SpecificTelemetryDTO 	    {
		 
				var telemetry_oid: Int?;
				    	 
		 
				var id: Int?;
				    	 
		 
				var name: String?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


					dictionary["telemetry_oid"] = self.telemetry_oid;
			

				
					dictionary["id"] = self.id;
				

				
					dictionary["name"] = self.name;
				
						
				return dictionary;
			}
		}
		
	