	
		//
		// StateTelemetryDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class StateTelemetryDTO :    		SpecificTelemetryDTO
	    {
		 
				var rangeStates: [StateDeviceDTO]?;
				    	 
	   	   
			// MARK: - Constructor
			
			
			override init ()
			{
				super.init();
			}
			override func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
				dictionary = super.toDictionary();
			


					dictionary["rangeStates"] = NSNull();
					if (self.rangeStates != nil)
					{
						var arrayOfDictionary: [[String : AnyObject]] = [];
						for item in self.rangeStates!
						{
							arrayOfDictionary.append(item.toDictionary());
						}
						
						dictionary["rangeStates"] = arrayOfDictionary;
					}
			
						
				return dictionary;
			}
		}
		
	