	
		//
		// TargetDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class TargetDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var goal_oid: Int?;
				    	 
		 
				var desiredValue: String?;
				    	 
		 
				var measure_oid: Int?;
				    	 
		 
				var description: String?;
				    	 
		 
				var dueDate: NSDate?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

					dictionary["goal_oid"] = self.goal_oid;
			

				
					dictionary["desiredValue"] = self.desiredValue;
				

					dictionary["measure_oid"] = self.measure_oid;
			

				
					dictionary["description"] = self.description;
				

				
					dictionary["dueDate"] = self.dueDate?.toString();
				
						
				return dictionary;
			}
		}
		
	