	
		//
		// TrademarkDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class TrademarkDTO 	    {
		 
				var id: Int?;
				    	 
		 
				var name: String?;
				    	 
		 
				var device_oid: [Int]?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["id"] = self.id;
				

				
					dictionary["name"] = self.name;
				

					dictionary["device_oid"] = self.device_oid;
			
						
				return dictionary;
			}
		}
		
	