	
		//
		// UserDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class UserDTO 	    {
		 
				var birthDate: NSDate?;
				    	 
		 
				var address: String?;
				    	 
		 
				var surnames: String?;
				    	 
		 
				var phone: String?;
				    	 
		 
				var photo: String?;
				    	 
		 
				var isActive: Bool?;
				    	 
		 
				var type: GenderType?;
				    	 
		 
				var isDiseased: Bool?;
				    	 
		 
				var pass: String?;
				    	 
		 
				var id: Int?;
				    	 
		 
				var name: String?;
				    	 
		 
				var description: String?;
				    	 
		 
				var email: String?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["birthDate"] = self.birthDate?.toString();
				

				
					dictionary["address"] = self.address;
				

				
					dictionary["surnames"] = self.surnames;
				

				
					dictionary["phone"] = self.phone;
				

				
					dictionary["photo"] = self.photo;
				

				
					dictionary["isActive"] = self.isActive;
				

				
					dictionary["type"] = self.type?.rawValue;
				

				
					dictionary["isDiseased"] = self.isDiseased;
				

				
					dictionary["pass"] = self.pass;
				

				
					dictionary["id"] = self.id;
				

				
					dictionary["name"] = self.name;
				

				
					dictionary["description"] = self.description;
				

				
					dictionary["email"] = self.email;
				
						
				return dictionary;
			}
		}
		
	