
package MoSIoTGenMosIoTRESTAzure.uiModels.DTO.enumerations;

/**
 * Code autogenerated. Do not modify this file.
 */
public enum AccessModeValue
{
	// region - Literals

	Auditory (1)
	,	Colour (2)
	,	ItemSize (3)
	,	Olfactory (4)
	,	Orientation (5)
	,	Position (6)
	,	Tactile (7)
	,	TextOnImage (8)
	,	Textual (9)
	,	Visual (10)
;

	// endregion


	// region - Members and constructor

	private final int rawValue;

	public int getRawValue ()
	{
		return this.rawValue;
	}

	AccessModeValue (int rawValue)
	{
		this.rawValue = rawValue;
	}

	// endregion


	// region - Public methods

	public static AccessModeValue fromRawValue (int rawValue)
	{
		AccessModeValue[] enumValues = AccessModeValue.values();

		for (int i = 0; i < enumValues.length; i++)
		{
			if (enumValues[i].Compare(rawValue))
			{
				return enumValues[i];
			}
		}

		return null;
	}

	public boolean Compare (int rawValue)
	{
		return this.rawValue == rawValue;
	}

	// endregion
	
}
