
package MoSIoTGenMosIoTRESTAzure.uiModels.DTO.enumerations;

/**
 * Code autogenerated. Do not modify this file.
 */
public enum AdaptationDetailValue
{
	// region - Literals

	Enhanced (1)
	,	RealTime (2)
	,	Record (3)
	,	Symbolic (4)
	,	Synthesized (5)
	,	Verbatim (6)
;

	// endregion


	// region - Members and constructor

	private final int rawValue;

	public int getRawValue ()
	{
		return this.rawValue;
	}

	AdaptationDetailValue (int rawValue)
	{
		this.rawValue = rawValue;
	}

	// endregion


	// region - Public methods

	public static AdaptationDetailValue fromRawValue (int rawValue)
	{
		AdaptationDetailValue[] enumValues = AdaptationDetailValue.values();

		for (int i = 0; i < enumValues.length; i++)
		{
			if (enumValues[i].Compare(rawValue))
			{
				return enumValues[i];
			}
		}

		return null;
	}

	public boolean Compare (int rawValue)
	{
		return this.rawValue == rawValue;
	}

	// endregion
	
}
