
package MoSIoTGenMosIoTRESTAzure.uiModels.DTO.enumerations;

/**
 * Code autogenerated. Do not modify this file.
 */
public enum TypeUnit
{
	// region - Literals

	Percent (1)
	,	Degrees_farenheit (2)
	,	Degrees_celsius (3)
	,	Geolocation (4)
	,	Steps (5)
	,	BeatsPerMinute (6)
;

	// endregion


	// region - Members and constructor

	private final int rawValue;

	public int getRawValue ()
	{
		return this.rawValue;
	}

	TypeUnit (int rawValue)
	{
		this.rawValue = rawValue;
	}

	// endregion


	// region - Public methods

	public static TypeUnit fromRawValue (int rawValue)
	{
		TypeUnit[] enumValues = TypeUnit.values();

		for (int i = 0; i < enumValues.length; i++)
		{
			if (enumValues[i].Compare(rawValue))
			{
				return enumValues[i];
			}
		}

		return null;
	}

	public boolean Compare (int rawValue)
	{
		return this.rawValue == rawValue;
	}

	// endregion
	
}
