
package MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTOA;

import MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.*;
import MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.utils.*;
import MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.enumerations.*;

import java.util.ArrayList;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Code autogenerated. Do not modify this file.
 */
public class AdaptationDetailRequiredDTOA extends DTOA
{
	// region - Members, getters and setters

	private Integer id;
	public Integer getId () { return id; }
	public void setId (Integer id) { this.id = id; }

	
	private AdaptationDetailValue adaptationRequest;
	public AdaptationDetailValue getAdaptationRequest () { return adaptationRequest; }
	public void setAdaptationRequest (AdaptationDetailValue adaptationRequest) { this.adaptationRequest = adaptationRequest; }
	
	private String description;
	public String getDescription () { return description; }
	public void setDescription (String description) { this.description = description; }
	
	
	
	
	// endregion
	
	
	
	// region - Constructor and JSON <-> DTOA <-> DTO
	
	public AdaptationDetailRequiredDTOA ()
	{
		// Empty constructor
	}
	
	@Override
	public void setFromJSON (JSONObject json)
	{
		try
		{
			if (!JSONObject.NULL.equals(json.opt("Id")))
			{
				this.id = (Integer) json.opt("Id");
			}
			

			if (!JSONObject.NULL.equals(json.opt("AdaptationRequest")))
			{
				int enumRawValue = (int) json.opt("AdaptationRequest");
				this.adaptationRequest = AdaptationDetailValue.fromRawValue(enumRawValue);
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Description")))
			{
			 
				this.description = (String) json.opt("Description");
			 
			}
			
			
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
	}
	
	public JSONObject toJSON ()
	{
		JSONObject json = new JSONObject();
		
		try
		{
			if (this.id != null){
				json.put("Id", this.id);
			}
			
		
		  if (this.adaptationRequest != null)
			json.put("AdaptationRequest", this.adaptationRequest.getRawValue());
		
		
		  if (this.description != null)
			json.put("Description", this.description);
		
			
			
		}
		catch (JSONException e)
		{
			e.printStackTrace();
		}
		
		return json;
	}
	
	@Override 
	public IDTO toDTO ()
	{
		AdaptationDetailRequiredDTO dto = new AdaptationDetailRequiredDTO ();
		
		// Attributes
		
	dto.setId (this.getId());

		
	dto.setAdaptationRequest (this.getAdaptationRequest());

	dto.setDescription (this.getDescription());

		
		
		// Roles
		
		
		return dto;
	}

	// endregion
}

	