
package MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTOA;

import MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.*;
import MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.utils.*;
import MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.enumerations.*;

import java.util.ArrayList;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Code autogenerated. Do not modify this file.
 */
public class AssociationDTOA extends DTOA
{
	// region - Members, getters and setters

	private Integer id;
	public Integer getId () { return id; }
	public void setId (Integer id) { this.id = id; }

	
	private String name;
	public String getName () { return name; }
	public void setName (String name) { this.name = name; }
	
	private String description;
	public String getDescription () { return description; }
	public void setDescription (String description) { this.description = description; }
	
	private AssociationType type;
	public AssociationType getType () { return type; }
	public void setType (AssociationType type) { this.type = type; }
	
	private CardinalityType cardinalityOrigin;
	public CardinalityType getCardinalityOrigin () { return cardinalityOrigin; }
	public void setCardinalityOrigin (CardinalityType cardinalityOrigin) { this.cardinalityOrigin = cardinalityOrigin; }
	
	private CardinalityType cardinalityTarget;
	public CardinalityType getCardinalityTarget () { return cardinalityTarget; }
	public void setCardinalityTarget (CardinalityType cardinalityTarget) { this.cardinalityTarget = cardinalityTarget; }
	
	
	
	
	// endregion
	
	
	
	// region - Constructor and JSON <-> DTOA <-> DTO
	
	public AssociationDTOA ()
	{
		// Empty constructor
	}
	
	@Override
	public void setFromJSON (JSONObject json)
	{
		try
		{
			if (!JSONObject.NULL.equals(json.opt("Id")))
			{
				this.id = (Integer) json.opt("Id");
			}
			

			if (!JSONObject.NULL.equals(json.opt("Name")))
			{
			 
				this.name = (String) json.opt("Name");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Description")))
			{
			 
				this.description = (String) json.opt("Description");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Type")))
			{
				int enumRawValue = (int) json.opt("Type");
				this.type = AssociationType.fromRawValue(enumRawValue);
			 
			}

			if (!JSONObject.NULL.equals(json.opt("CardinalityOrigin")))
			{
				int enumRawValue = (int) json.opt("CardinalityOrigin");
				this.cardinalityOrigin = CardinalityType.fromRawValue(enumRawValue);
			 
			}

			if (!JSONObject.NULL.equals(json.opt("CardinalityTarget")))
			{
				int enumRawValue = (int) json.opt("CardinalityTarget");
				this.cardinalityTarget = CardinalityType.fromRawValue(enumRawValue);
			 
			}
			
			
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
	}
	
	public JSONObject toJSON ()
	{
		JSONObject json = new JSONObject();
		
		try
		{
			if (this.id != null){
				json.put("Id", this.id);
			}
			
		
		  if (this.name != null)
			json.put("Name", this.name);
		
		
		  if (this.description != null)
			json.put("Description", this.description);
		
		
		  if (this.type != null)
			json.put("Type", this.type.getRawValue());
		
		
		  if (this.cardinalityOrigin != null)
			json.put("CardinalityOrigin", this.cardinalityOrigin.getRawValue());
		
		
		  if (this.cardinalityTarget != null)
			json.put("CardinalityTarget", this.cardinalityTarget.getRawValue());
		
			
			
		}
		catch (JSONException e)
		{
			e.printStackTrace();
		}
		
		return json;
	}
	
	@Override 
	public IDTO toDTO ()
	{
		AssociationDTO dto = new AssociationDTO ();
		
		// Attributes
		
	dto.setId (this.getId());

		
	dto.setName (this.getName());

	dto.setDescription (this.getDescription());

	dto.setType (this.getType());

	dto.setCardinalityOrigin (this.getCardinalityOrigin());

	dto.setCardinalityTarget (this.getCardinalityTarget());

		
		
		// Roles
		
		
		return dto;
	}

	// endregion
}

	