
package MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTOA;

import MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.*;
import MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.utils.*;
import MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.enumerations.*;

import java.util.ArrayList;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Code autogenerated. Do not modify this file.
 */
public class CareActivityDTOA extends DTOA
{
	// region - Members, getters and setters

	private Integer id;
	public Integer getId () { return id; }
	public void setId (Integer id) { this.id = id; }

	
	private String name;
	public String getName () { return name; }
	public void setName (String name) { this.name = name; }
	
	private String description;
	public String getDescription () { return description; }
	public void setDescription (String description) { this.description = description; }
	
	private TypePeriodicity periodicity;
	public TypePeriodicity getPeriodicity () { return periodicity; }
	public void setPeriodicity (TypePeriodicity periodicity) { this.periodicity = periodicity; }
	
	private Integer duration;
	public Integer getDuration () { return duration; }
	public void setDuration (Integer duration) { this.duration = duration; }
	
	private String location;
	public String getLocation () { return location; }
	public void setLocation (String location) { this.location = location; }
	
	private String outcomeCode;
	public String getOutcomeCode () { return outcomeCode; }
	public void setOutcomeCode (String outcomeCode) { this.outcomeCode = outcomeCode; }
	
	private TypeActivity typeActivity;
	public TypeActivity getTypeActivity () { return typeActivity; }
	public void setTypeActivity (TypeActivity typeActivity) { this.typeActivity = typeActivity; }
	
	private String activityCode;
	public String getActivityCode () { return activityCode; }
	public void setActivityCode (String activityCode) { this.activityCode = activityCode; }
	
	
	/* Rol: CareActivity o--> Comunication */
	private ArrayList<ComunicationDTOA> comunications;
	public ArrayList<ComunicationDTOA> getComunications () { return comunications; }
	public void setComunications (ArrayList<ComunicationDTOA> comunications) { this.comunications = comunications; }

	/* Rol: CareActivity o--> Appointment */
	private AppointmentDTOA appointments;
	public AppointmentDTOA getAppointments () { return appointments; }
	public void setAppointments (AppointmentDTOA appointments) { this.appointments = appointments; }

	/* Rol: CareActivity o--> Medication */
	private MedicationDTOA medications;
	public MedicationDTOA getMedications () { return medications; }
	public void setMedications (MedicationDTOA medications) { this.medications = medications; }

	/* Rol: CareActivity o--> NutritionOrder */
	private NutritionOrderDTOA nutritionOrders;
	public NutritionOrderDTOA getNutritionOrders () { return nutritionOrders; }
	public void setNutritionOrders (NutritionOrderDTOA nutritionOrders) { this.nutritionOrders = nutritionOrders; }

	
	
	// endregion
	
	
	
	// region - Constructor and JSON <-> DTOA <-> DTO
	
	public CareActivityDTOA ()
	{
		// Empty constructor
	}
	
	@Override
	public void setFromJSON (JSONObject json)
	{
		try
		{
			if (!JSONObject.NULL.equals(json.opt("Id")))
			{
				this.id = (Integer) json.opt("Id");
			}
			

			if (!JSONObject.NULL.equals(json.opt("Name")))
			{
			 
				this.name = (String) json.opt("Name");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Description")))
			{
			 
				this.description = (String) json.opt("Description");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Periodicity")))
			{
				int enumRawValue = (int) json.opt("Periodicity");
				this.periodicity = TypePeriodicity.fromRawValue(enumRawValue);
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Duration")))
			{
			 
				this.duration = (Integer) json.opt("Duration");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Location")))
			{
			 
				this.location = (String) json.opt("Location");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("OutcomeCode")))
			{
			 
				this.outcomeCode = (String) json.opt("OutcomeCode");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("TypeActivity")))
			{
				int enumRawValue = (int) json.opt("TypeActivity");
				this.typeActivity = TypeActivity.fromRawValue(enumRawValue);
			 
			}

			if (!JSONObject.NULL.equals(json.opt("ActivityCode")))
			{
			 
				this.activityCode = (String) json.opt("ActivityCode");
			 
			}
			

			JSONObject jsonComunications = json.optJSONObject("Comunications");
			if (jsonComunications != null)
			{
				ComunicationDTOA tmp = new ComunicationDTOA();
				tmp.setFromJSON(jsonComunications);
				this.comunications = tmp;
			}


			JSONObject jsonAppointments = json.optJSONObject("Appointments");
			if (jsonAppointments != null)
			{
				AppointmentDTOA tmp = new AppointmentDTOA();
				tmp.setFromJSON(jsonAppointments);
				this.appointments = tmp;
			}


			JSONObject jsonMedications = json.optJSONObject("Medications");
			if (jsonMedications != null)
			{
				MedicationDTOA tmp = new MedicationDTOA();
				tmp.setFromJSON(jsonMedications);
				this.medications = tmp;
			}


			JSONObject jsonNutritionOrders = json.optJSONObject("NutritionOrders");
			if (jsonNutritionOrders != null)
			{
				NutritionOrderDTOA tmp = new NutritionOrderDTOA();
				tmp.setFromJSON(jsonNutritionOrders);
				this.nutritionOrders = tmp;
			}

			
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
	}
	
	public JSONObject toJSON ()
	{
		JSONObject json = new JSONObject();
		
		try
		{
			if (this.id != null){
				json.put("Id", this.id);
			}
			
		
		  if (this.name != null)
			json.put("Name", this.name);
		
		
		  if (this.description != null)
			json.put("Description", this.description);
		
		
		  if (this.periodicity != null)
			json.put("Periodicity", this.periodicity.getRawValue());
		
		
		  if (this.duration != null)
			json.put("Duration", this.duration.intValue());
		
		
		  if (this.location != null)
			json.put("Location", this.location);
		
		
		  if (this.outcomeCode != null)
			json.put("OutcomeCode", this.outcomeCode);
		
		
		  if (this.typeActivity != null)
			json.put("TypeActivity", this.typeActivity.getRawValue());
		
		
		  if (this.activityCode != null)
			json.put("ActivityCode", this.activityCode);
		
			

			if (this.comunications != null)
			{
				json.put("Comunications", this.comunications.toJSON());
			}


			if (this.appointments != null)
			{
				json.put("Appointments", this.appointments.toJSON());
			}


			if (this.medications != null)
			{
				json.put("Medications", this.medications.toJSON());
			}


			if (this.nutritionOrders != null)
			{
				json.put("NutritionOrders", this.nutritionOrders.toJSON());
			}

			
		}
		catch (JSONException e)
		{
			e.printStackTrace();
		}
		
		return json;
	}
	
	@Override 
	public IDTO toDTO ()
	{
		CareActivityDTO dto = new CareActivityDTO ();
		
		// Attributes
		
	dto.setId (this.getId());

		
	dto.setName (this.getName());

	dto.setDescription (this.getDescription());

	dto.setPeriodicity (this.getPeriodicity());

	dto.setDuration (this.getDuration());

	dto.setLocation (this.getLocation());

	dto.setOutcomeCode (this.getOutcomeCode());

	dto.setTypeActivity (this.getTypeActivity());

	dto.setActivityCode (this.getActivityCode());

		
		
		// Roles
					// TODO: from DTOA [ Comunications ] (dataType : ArrayList<ComunicationDTOA>) to DTO [ Notification ]
					// TODO: from DTOA [ Appointments ] (dataType : AppointmentDTOA) to DTO [ Appointment ]
					// TODO: from DTOA [ Medications ] (dataType : MedicationDTOA) to DTO [ Medication ]
					// TODO: from DTOA [ NutritionOrders ] (dataType : NutritionOrderDTOA) to DTO [ NutritionOrder ]
		
		
		return dto;
	}

	// endregion
}

	