
package MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTOA;

import MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.*;
import MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.utils.*;
import MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.enumerations.*;

import java.util.ArrayList;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Code autogenerated. Do not modify this file.
 */
public class IMAdaptationDetailDTOA extends DTOA
{
	// region - Members, getters and setters

	private Integer id;
	public Integer getId () { return id; }
	public void setId (Integer id) { this.id = id; }

	
	private String name;
	public String getName () { return name; }
	public void setName (String name) { this.name = name; }
	
	private String description;
	public String getDescription () { return description; }
	public void setDescription (String description) { this.description = description; }
	
	
	/* Rol: IMAdaptationDetail o--> AdaptationDetailRequired */
	private AdaptationDetailRequiredDTOA valueAdaptionDetail;
	public AdaptationDetailRequiredDTOA getValueAdaptionDetail () { return valueAdaptionDetail; }
	public void setValueAdaptionDetail (AdaptationDetailRequiredDTOA valueAdaptionDetail) { this.valueAdaptionDetail = valueAdaptionDetail; }

	
	
	// endregion
	
	
	
	// region - Constructor and JSON <-> DTOA <-> DTO
	
	public IMAdaptationDetailDTOA ()
	{
		// Empty constructor
	}
	
	@Override
	public void setFromJSON (JSONObject json)
	{
		try
		{
			if (!JSONObject.NULL.equals(json.opt("Id")))
			{
				this.id = (Integer) json.opt("Id");
			}
			

			if (!JSONObject.NULL.equals(json.opt("Name")))
			{
			 
				this.name = (String) json.opt("Name");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Description")))
			{
			 
				this.description = (String) json.opt("Description");
			 
			}
			

			JSONObject jsonValueAdaptionDetail = json.optJSONObject("ValueAdaptionDetail");
			if (jsonValueAdaptionDetail != null)
			{
				AdaptationDetailRequiredDTOA tmp = new AdaptationDetailRequiredDTOA();
				tmp.setFromJSON(jsonValueAdaptionDetail);
				this.valueAdaptionDetail = tmp;
			}

			
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
	}
	
	public JSONObject toJSON ()
	{
		JSONObject json = new JSONObject();
		
		try
		{
			if (this.id != null){
				json.put("Id", this.id);
			}
			
		
		  if (this.name != null)
			json.put("Name", this.name);
		
		
		  if (this.description != null)
			json.put("Description", this.description);
		
			

			if (this.valueAdaptionDetail != null)
			{
				json.put("ValueAdaptionDetail", this.valueAdaptionDetail.toJSON());
			}

			
		}
		catch (JSONException e)
		{
			e.printStackTrace();
		}
		
		return json;
	}
	
	@Override 
	public IDTO toDTO ()
	{
		IMAdaptationDetailDTO dto = new IMAdaptationDetailDTO ();
		
		// Attributes
		
	dto.setId (this.getId());

		
	dto.setName (this.getName());

	dto.setDescription (this.getDescription());

		
		
		// Roles
					// TODO: from DTOA [ ValueAdaptionDetail ] (dataType : AdaptationDetailRequiredDTOA) to DTO [ AdaptationDetailRequired ]
		
		
		return dto;
	}

	// endregion
}

	