
package MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTOA;

import MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.*;
import MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.utils.*;
import MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.enumerations.*;

import java.util.ArrayList;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Code autogenerated. Do not modify this file.
 */
public class IMAdaptationTypeDTOA extends DTOA
{
	// region - Members, getters and setters

	private Integer id;
	public Integer getId () { return id; }
	public void setId (Integer id) { this.id = id; }

	
	private String name;
	public String getName () { return name; }
	public void setName (String name) { this.name = name; }
	
	private String description;
	public String getDescription () { return description; }
	public void setDescription (String description) { this.description = description; }
	
	
	/* Rol: IMAdaptationType o--> AdaptationTypeRequired */
	private AdaptationTypeRequiredDTOA valueAdaptionType;
	public AdaptationTypeRequiredDTOA getValueAdaptionType () { return valueAdaptionType; }
	public void setValueAdaptionType (AdaptationTypeRequiredDTOA valueAdaptionType) { this.valueAdaptionType = valueAdaptionType; }

	
	
	// endregion
	
	
	
	// region - Constructor and JSON <-> DTOA <-> DTO
	
	public IMAdaptationTypeDTOA ()
	{
		// Empty constructor
	}
	
	@Override
	public void setFromJSON (JSONObject json)
	{
		try
		{
			if (!JSONObject.NULL.equals(json.opt("Id")))
			{
				this.id = (Integer) json.opt("Id");
			}
			

			if (!JSONObject.NULL.equals(json.opt("Name")))
			{
			 
				this.name = (String) json.opt("Name");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Description")))
			{
			 
				this.description = (String) json.opt("Description");
			 
			}
			

			JSONObject jsonValueAdaptionType = json.optJSONObject("ValueAdaptionType");
			if (jsonValueAdaptionType != null)
			{
				AdaptationTypeRequiredDTOA tmp = new AdaptationTypeRequiredDTOA();
				tmp.setFromJSON(jsonValueAdaptionType);
				this.valueAdaptionType = tmp;
			}

			
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
	}
	
	public JSONObject toJSON ()
	{
		JSONObject json = new JSONObject();
		
		try
		{
			if (this.id != null){
				json.put("Id", this.id);
			}
			
		
		  if (this.name != null)
			json.put("Name", this.name);
		
		
		  if (this.description != null)
			json.put("Description", this.description);
		
			

			if (this.valueAdaptionType != null)
			{
				json.put("ValueAdaptionType", this.valueAdaptionType.toJSON());
			}

			
		}
		catch (JSONException e)
		{
			e.printStackTrace();
		}
		
		return json;
	}
	
	@Override 
	public IDTO toDTO ()
	{
		IMAdaptationTypeDTO dto = new IMAdaptationTypeDTO ();
		
		// Attributes
		
	dto.setId (this.getId());

		
	dto.setName (this.getName());

	dto.setDescription (this.getDescription());

		
		
		// Roles
					// TODO: from DTOA [ ValueAdaptionType ] (dataType : AdaptationTypeRequiredDTOA) to DTO [ AdaptationTypeRequired ]
		
		
		return dto;
	}

	// endregion
}

	