
package MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTOA;

import MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.*;
import MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.utils.*;
import MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.enumerations.*;

import java.util.ArrayList;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Code autogenerated. Do not modify this file.
 */
public class IMGoalDTOA extends DTOA
{
	// region - Members, getters and setters

	private Integer id;
	public Integer getId () { return id; }
	public void setId (Integer id) { this.id = id; }

	
	private String name;
	public String getName () { return name; }
	public void setName (String name) { this.name = name; }
	
	private String description;
	public String getDescription () { return description; }
	public void setDescription (String description) { this.description = description; }
	
	private String value;
	public String getValue () { return value; }
	public void setValue (String value) { this.value = value; }
	
	
	/* Rol: IMGoal o--> Goal */
	private GoalDTOA valueGoal;
	public GoalDTOA getValueGoal () { return valueGoal; }
	public void setValueGoal (GoalDTOA valueGoal) { this.valueGoal = valueGoal; }

	
	
	// endregion
	
	
	
	// region - Constructor and JSON <-> DTOA <-> DTO
	
	public IMGoalDTOA ()
	{
		// Empty constructor
	}
	
	@Override
	public void setFromJSON (JSONObject json)
	{
		try
		{
			if (!JSONObject.NULL.equals(json.opt("Id")))
			{
				this.id = (Integer) json.opt("Id");
			}
			

			if (!JSONObject.NULL.equals(json.opt("Name")))
			{
			 
				this.name = (String) json.opt("Name");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Description")))
			{
			 
				this.description = (String) json.opt("Description");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Value")))
			{
			 
				this.value = (String) json.opt("Value");
			 
			}
			

			JSONObject jsonValueGoal = json.optJSONObject("ValueGoal");
			if (jsonValueGoal != null)
			{
				GoalDTOA tmp = new GoalDTOA();
				tmp.setFromJSON(jsonValueGoal);
				this.valueGoal = tmp;
			}

			
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
	}
	
	public JSONObject toJSON ()
	{
		JSONObject json = new JSONObject();
		
		try
		{
			if (this.id != null){
				json.put("Id", this.id);
			}
			
		
		  if (this.name != null)
			json.put("Name", this.name);
		
		
		  if (this.description != null)
			json.put("Description", this.description);
		
		
		  if (this.value != null)
			json.put("Value", this.value);
		
			

			if (this.valueGoal != null)
			{
				json.put("ValueGoal", this.valueGoal.toJSON());
			}

			
		}
		catch (JSONException e)
		{
			e.printStackTrace();
		}
		
		return json;
	}
	
	@Override 
	public IDTO toDTO ()
	{
		IMGoalDTO dto = new IMGoalDTO ();
		
		// Attributes
		
	dto.setId (this.getId());

		
	dto.setName (this.getName());

	dto.setDescription (this.getDescription());

	dto.setValue (this.getValue());

		
		
		// Roles
					// TODO: from DTOA [ ValueGoal ] (dataType : GoalDTOA) to DTO [ Goal ]
		
		
		return dto;
	}

	// endregion
}

	