
package MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTOA;

import MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.*;
import MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.utils.*;
import MoSIoTGenScenarioMoSIoTRESTAzure.uiModels.DTO.enumerations.*;

import java.util.ArrayList;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Code autogenerated. Do not modify this file.
 */
public class IMPropertyDTOA extends DTOA
{
	// region - Members, getters and setters

	private Integer id;
	public Integer getId () { return id; }
	public void setId (Integer id) { this.id = id; }

	
	private String name;
	public String getName () { return name; }
	public void setName (String name) { this.name = name; }
	
	private DataType type;
	public DataType getType () { return type; }
	public void setType (DataType type) { this.type = type; }
	
	private String value;
	public String getValue () { return value; }
	public void setValue (String value) { this.value = value; }
	
	
	/* Rol: IMProperty o--> Property */
	private PropertyDTOA valueProperty;
	public PropertyDTOA getValueProperty () { return valueProperty; }
	public void setValueProperty (PropertyDTOA valueProperty) { this.valueProperty = valueProperty; }

	
	
	// endregion
	
	
	
	// region - Constructor and JSON <-> DTOA <-> DTO
	
	public IMPropertyDTOA ()
	{
		// Empty constructor
	}
	
	@Override
	public void setFromJSON (JSONObject json)
	{
		try
		{
			if (!JSONObject.NULL.equals(json.opt("Id")))
			{
				this.id = (Integer) json.opt("Id");
			}
			

			if (!JSONObject.NULL.equals(json.opt("Name")))
			{
			 
				this.name = (String) json.opt("Name");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Type")))
			{
				int enumRawValue = (int) json.opt("Type");
				this.type = DataType.fromRawValue(enumRawValue);
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Value")))
			{
			 
				this.value = (String) json.opt("Value");
			 
			}
			

			JSONObject jsonValueProperty = json.optJSONObject("ValueProperty");
			if (jsonValueProperty != null)
			{
				PropertyDTOA tmp = new PropertyDTOA();
				tmp.setFromJSON(jsonValueProperty);
				this.valueProperty = tmp;
			}

			
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
	}
	
	public JSONObject toJSON ()
	{
		JSONObject json = new JSONObject();
		
		try
		{
			if (this.id != null){
				json.put("Id", this.id);
			}
			
		
		  if (this.name != null)
			json.put("Name", this.name);
		
		
		  if (this.type != null)
			json.put("Type", this.type.getRawValue());
		
		
		  if (this.value != null)
			json.put("Value", this.value);
		
			

			if (this.valueProperty != null)
			{
				json.put("ValueProperty", this.valueProperty.toJSON());
			}

			
		}
		catch (JSONException e)
		{
			e.printStackTrace();
		}
		
		return json;
	}
	
	@Override 
	public IDTO toDTO ()
	{
		IMPropertyDTO dto = new IMPropertyDTO ();
		
		// Attributes
		
	dto.setId (this.getId());

		
	dto.setName (this.getName());

	dto.setType (this.getType());

	dto.setValue (this.getValue());

		
		
		// Roles
					// TODO: from DTOA [ ValueProperty ] (dataType : PropertyDTOA) to DTO [ Property ]
		
		
		return dto;
	}

	// endregion
}

	