	
		package MoSIoTGenMosIoTRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  MoSIoTGenMosIoTRESTAzure.uiModels.DTO.utils.*;
		import  MoSIoTGenMosIoTRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class AssociationDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private String name;
				public String getName () { return name; } 
				public void setName  (String value) { name = value;  } 
				    	 
				private Integer rolOrigin_oid;
				public Integer  getRolOrigin_oid () { return rolOrigin_oid; } 
				public void setRolOrigin_oid (Integer value) { rolOrigin_oid = value;  } 
				    	 
				private Integer rolTarget_oid;
				public Integer  getRolTarget_oid () { return rolTarget_oid; } 
				public void setRolTarget_oid (Integer value) { rolTarget_oid = value;  } 
				    	 
				private AssociationType type;
				public AssociationType getType () { return type; } 
				public void setType  (AssociationType value) { type = value;  } 
				    	 
				private CardinalityType cardinalityOrigin;
				public CardinalityType getCardinalityOrigin () { return cardinalityOrigin; } 
				public void setCardinalityOrigin  (CardinalityType value) { cardinalityOrigin = value;  } 
				    	 
				private CardinalityType cardinalityTarget;
				public CardinalityType getCardinalityTarget () { return cardinalityTarget; } 
				public void setCardinalityTarget  (CardinalityType value) { cardinalityTarget = value;  } 
				    	 
				private Integer entityOrigin_oid;
				public Integer  getEntityOrigin_oid () { return entityOrigin_oid; } 
				public void setEntityOrigin_oid (Integer value) { entityOrigin_oid = value;  } 
				    	 
				private Integer entityTarget_oid;
				public Integer  getEntityTarget_oid () { return entityTarget_oid; } 
				public void setEntityTarget_oid (Integer value) { entityTarget_oid = value;  } 
				    	 
				private Integer ioTScenario_oid;
				public Integer  getIoTScenario_oid () { return ioTScenario_oid; } 
				public void setIoTScenario_oid (Integer value) { ioTScenario_oid = value;  } 
				    	 
				private String description;
				public String getDescription () { return description; } 
				public void setDescription  (String value) { description = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				
				
						  json.put("Name", this.name);
				

						if (this.rolOrigin_oid != null)
						{
							json.put("RolOrigin_oid", this.rolOrigin_oid.intValue());
						}

						if (this.rolTarget_oid != null)
						{
							json.put("RolTarget_oid", this.rolTarget_oid.intValue());
						}
				
						  json.put("Type", this.type.getRawValue());
				
				
						  json.put("CardinalityOrigin", this.cardinalityOrigin.getRawValue());
				
				
						  json.put("CardinalityTarget", this.cardinalityTarget.getRawValue());
				

						if (this.entityOrigin_oid != null)
						{
							json.put("EntityOrigin_oid", this.entityOrigin_oid.intValue());
						}

						if (this.entityTarget_oid != null)
						{
							json.put("EntityTarget_oid", this.entityTarget_oid.intValue());
						}

						if (this.ioTScenario_oid != null)
						{
							json.put("IoTScenario_oid", this.ioTScenario_oid.intValue());
						}
				
						  json.put("Description", this.description);
				
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	