	
		package MoSIoTGenMosIoTRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  MoSIoTGenMosIoTRESTAzure.uiModels.DTO.utils.*;
		import  MoSIoTGenMosIoTRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class EntityAttributesDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private String name;
				public String getName () { return name; } 
				public void setName  (String value) { name = value;  } 
				    	 
				private DataType type;
				public DataType getType () { return type; } 
				public void setType  (DataType value) { type = value;  } 
				    	 
				private Boolean isOID;
				public Boolean getIsOID () { return isOID; } 
				public void setIsOID  (Boolean value) { isOID = value;  } 
				    	 
				private ArrayList<Integer> targetAssociation_oid;
				public ArrayList<Integer>  getTargetAssociation_oid () { return targetAssociation_oid; } 
				public void setTargetAssociation_oid (ArrayList<Integer> value) { targetAssociation_oid = value;  } 
				    	 
				private ArrayList<Integer> originAsociation_oid;
				public ArrayList<Integer>  getOriginAsociation_oid () { return originAsociation_oid; } 
				public void setOriginAsociation_oid (ArrayList<Integer> value) { originAsociation_oid = value;  } 
				    	 
				private AssociationType associationType;
				public AssociationType getAssociationType () { return associationType; } 
				public void setAssociationType  (AssociationType value) { associationType = value;  } 
				    	 
				private Boolean isWritable;
				public Boolean getIsWritable () { return isWritable; } 
				public void setIsWritable  (Boolean value) { isWritable = value;  } 
				    	 
				private String description;
				public String getDescription () { return description; } 
				public void setDescription  (String value) { description = value;  } 
				    	 
				private Integer entity_oid;
				public Integer  getEntity_oid () { return entity_oid; } 
				public void setEntity_oid (Integer value) { entity_oid = value;  } 
				    	 
				private ArrayList<Integer> trigger_oid;
				public ArrayList<Integer>  getTrigger_oid () { return trigger_oid; } 
				public void setTrigger_oid (ArrayList<Integer> value) { trigger_oid = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				
				
						  json.put("Name", this.name);
				
				
						  json.put("Type", this.type.getRawValue());
				
				
						  json.put("IsOID", this.isOID);
				

						if (this.targetAssociation_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.targetAssociation_oid.size(); ++i)
							{
								jsonArray.put(this.targetAssociation_oid.get(i));
							}
							json.put("TargetAssociation_oid", jsonArray);
						}
		

						if (this.originAsociation_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.originAsociation_oid.size(); ++i)
							{
								jsonArray.put(this.originAsociation_oid.get(i));
							}
							json.put("OriginAsociation_oid", jsonArray);
						}
		
				
						  json.put("AssociationType", this.associationType.getRawValue());
				
				
						  json.put("IsWritable", this.isWritable);
				
				
						  json.put("Description", this.description);
				

						if (this.entity_oid != null)
						{
							json.put("Entity_oid", this.entity_oid.intValue());
						}

						if (this.trigger_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.trigger_oid.size(); ++i)
							{
								jsonArray.put(this.trigger_oid.get(i));
							}
							json.put("Trigger_oid", jsonArray);
						}
		
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	