	
		package MoSIoTGenMosIoTRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  MoSIoTGenMosIoTRESTAzure.uiModels.DTO.utils.*;
		import  MoSIoTGenMosIoTRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class IMAdaptationRequestDTO extends    		EntityAttributesDTO
	    implements IDTO
	    {
				private Integer adaptationRequest_oid;
				public Integer  getAdaptationRequest_oid () { return adaptationRequest_oid; } 
				public void setAdaptationRequest_oid (Integer value) { adaptationRequest_oid = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{

						if (this.adaptationRequest_oid != null)
						{
							json.put("AdaptationRequest_oid", this.adaptationRequest_oid.intValue());
						}
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	