	
		package MoSIoTGenMosIoTRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  MoSIoTGenMosIoTRESTAzure.uiModels.DTO.utils.*;
		import  MoSIoTGenMosIoTRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class NotificationDTO 	    implements IDTO
	    {
				private SeverityEvent severity;
				public SeverityEvent getSeverity () { return severity; } 
				public void setSeverity  (SeverityEvent value) { severity = value;  } 
				    	 
				private String message;
				public String getMessage () { return message; } 
				public void setMessage  (String value) { message = value;  } 
				    	 
				private java.util.Date sendDate;
				public java.util.Date getSendDate () { return sendDate; } 
				public void setSendDate  (java.util.Date value) { sendDate = value;  } 
				    	 
				private ArrayList<String> receivers_oid;
				public ArrayList<String>  getReceivers_oid () { return receivers_oid; } 
				public void setReceivers_oid (ArrayList<String> value) { receivers_oid = value;  } 
				    	 
				private Integer carePlan_oid;
				public Integer  getCarePlan_oid () { return carePlan_oid; } 
				public void setCarePlan_oid (Integer value) { carePlan_oid = value;  } 
				    	 
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Severity", this.severity.getRawValue());
				
				
						  json.put("Message", this.message);
				
				
						  json.put("SendDate", DateUtils.dateToFormatString(this.sendDate));
				

						if (this.receivers_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.receivers_oid.size(); ++i)
							{
								jsonArray.put(this.receivers_oid.get(i));
							}
							json.put("Receivers_oid", jsonArray);
						}
		

						if (this.carePlan_oid != null)
						{
							json.put("CarePlan_oid", this.carePlan_oid.intValue());
						}
				
						  json.put("Id", this.id.intValue());
				
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	