	
		package MoSIoTGenMosIoTRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  MoSIoTGenMosIoTRESTAzure.uiModels.DTO.utils.*;
		import  MoSIoTGenMosIoTRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class NotificationUserDTO 	    implements IDTO
	    {
				private Integer notification_oid;
				public Integer  getNotification_oid () { return notification_oid; } 
				public void setNotification_oid (Integer value) { notification_oid = value;  } 
				    	 
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private String user_oid;
				public String  getUser_oid () { return user_oid; } 
				public void setUser_oid (String value) { user_oid = value;  } 
				    	 
				private Boolean isReceived;
				public Boolean getIsReceived () { return isReceived; } 
				public void setIsReceived  (Boolean value) { isReceived = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{

						if (this.notification_oid != null)
						{
							json.put("Notification_oid", this.notification_oid.intValue());
						}
				
						  json.put("Id", this.id.intValue());
				

						if (this.user_oid != null)
						{
							json.put("User_oid", this.user_oid);
						}
				
						  json.put("IsReceived", this.isReceived);
				
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	