	
		package MoSIoTGenMosIoTRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  MoSIoTGenMosIoTRESTAzure.uiModels.DTO.utils.*;
		import  MoSIoTGenMosIoTRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class NutritionOrderDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private String description;
				public String getDescription () { return description; } 
				public void setDescription  (String value) { description = value;  } 
				    	 
				private String dietCode;
				public String getDietCode () { return dietCode; } 
				public void setDietCode  (String value) { dietCode = value;  } 
				    	 
				private Integer careActivity_oid;
				public Integer  getCareActivity_oid () { return careActivity_oid; } 
				public void setCareActivity_oid (Integer value) { careActivity_oid = value;  } 
				    	 
				private String name;
				public String getName () { return name; } 
				public void setName  (String value) { name = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				
				
						  json.put("Description", this.description);
				
				
						  json.put("DietCode", this.dietCode);
				

						if (this.careActivity_oid != null)
						{
							json.put("CareActivity_oid", this.careActivity_oid.intValue());
						}
				
						  json.put("Name", this.name);
				
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	