	
		package MoSIoTGenMosIoTRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  MoSIoTGenMosIoTRESTAzure.uiModels.DTO.utils.*;
		import  MoSIoTGenMosIoTRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class RecipeActionDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private Integer recipe_oid;
				public Integer  getRecipe_oid () { return recipe_oid; } 
				public void setRecipe_oid (Integer value) { recipe_oid = value;  } 
				    	 
				private Integer operation_oid;
				public Integer  getOperation_oid () { return operation_oid; } 
				public void setOperation_oid (Integer value) { operation_oid = value;  } 
				    	 
				private String name;
				public String getName () { return name; } 
				public void setName  (String value) { name = value;  } 
				    	 
				private String description;
				public String getDescription () { return description; } 
				public void setDescription  (String value) { description = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				

						if (this.recipe_oid != null)
						{
							json.put("Recipe_oid", this.recipe_oid.intValue());
						}

						if (this.operation_oid != null)
						{
							json.put("Operation_oid", this.operation_oid.intValue());
						}
				
						  json.put("Name", this.name);
				
				
						  json.put("Description", this.description);
				
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	