	
		package MoSIoTGenMosIoTRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  MoSIoTGenMosIoTRESTAzure.uiModels.DTO.utils.*;
		import  MoSIoTGenMosIoTRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class StateTelemetryDTO extends    		SpecificTelemetryDTO
	    implements IDTO
	    {
				private ArrayList<StateDeviceDTO> rangeStates;
				public ArrayList<StateDeviceDTO> getRangeStates () { return rangeStates; } 
				public void setRangeStates (ArrayList<StateDeviceDTO> value) { rangeStates = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{

						if (this.rangeStates != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.rangeStates.size(); ++i)
							{
								jsonArray.put(this.rangeStates.get(i).toJSON());
							}
							json.put("RangeStates", jsonArray);
						}
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	