	
		package MoSIoTGenMosIoTRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  MoSIoTGenMosIoTRESTAzure.uiModels.DTO.utils.*;
		import  MoSIoTGenMosIoTRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class TelemetryDTO 	    implements IDTO
	    {
				private Integer deviceTemplate_oid;
				public Integer  getDeviceTemplate_oid () { return deviceTemplate_oid; } 
				public void setDeviceTemplate_oid (Integer value) { deviceTemplate_oid = value;  } 
				    	 
				private Double frecuency;
				public Double getFrecuency () { return frecuency; } 
				public void setFrecuency  (Double value) { frecuency = value;  } 
				    	 
				private Integer typeTelemetry_oid;
				public Integer  getTypeTelemetry_oid () { return typeTelemetry_oid; } 
				public void setTypeTelemetry_oid (Integer value) { typeTelemetry_oid = value;  } 
				    	 
				private DataType schema;
				public DataType getSchema () { return schema; } 
				public void setSchema  (DataType value) { schema = value;  } 
				    	 
				private TypeUnit unit;
				public TypeUnit getUnit () { return unit; } 
				public void setUnit  (TypeUnit value) { unit = value;  } 
				    	 
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private String name;
				public String getName () { return name; } 
				public void setName  (String value) { name = value;  } 
				    	 
				private TelemetryType type;
				public TelemetryType getType () { return type; } 
				public void setType  (TelemetryType value) { type = value;  } 
				    	 
				private ArrayList<Integer> properties_oid;
				public ArrayList<Integer>  getProperties_oid () { return properties_oid; } 
				public void setProperties_oid (ArrayList<Integer> value) { properties_oid = value;  } 
				    	 
				private Integer vitalSign_oid;
				public Integer  getVitalSign_oid () { return vitalSign_oid; } 
				public void setVitalSign_oid (Integer value) { vitalSign_oid = value;  } 
				    	 
				private ArrayList<Integer> iMTelemetry_oid;
				public ArrayList<Integer>  getIMTelemetry_oid () { return iMTelemetry_oid; } 
				public void setIMTelemetry_oid (ArrayList<Integer> value) { iMTelemetry_oid = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{

						if (this.deviceTemplate_oid != null)
						{
							json.put("DeviceTemplate_oid", this.deviceTemplate_oid.intValue());
						}
				
						  json.put("Frecuency", this.frecuency);
				

						if (this.typeTelemetry_oid != null)
						{
							json.put("TypeTelemetry_oid", this.typeTelemetry_oid.intValue());
						}
				
						  json.put("Schema", this.schema.getRawValue());
				
				
						  json.put("Unit", this.unit.getRawValue());
				
				
						  json.put("Id", this.id.intValue());
				
				
						  json.put("Name", this.name);
				
				
						  json.put("Type", this.type.getRawValue());
				

						if (this.properties_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.properties_oid.size(); ++i)
							{
								jsonArray.put(this.properties_oid.get(i));
							}
							json.put("Properties_oid", jsonArray);
						}
		

						if (this.vitalSign_oid != null)
						{
							json.put("VitalSign_oid", this.vitalSign_oid.intValue());
						}

						if (this.iMTelemetry_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.iMTelemetry_oid.size(); ++i)
							{
								jsonArray.put(this.iMTelemetry_oid.get(i));
							}
							json.put("IMTelemetry_oid", jsonArray);
						}
		
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	