//
// AdaptationDetailRequiredDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class AdaptationDetailRequiredDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	var adaptationRequest: AdaptationDetailValue?;
	var description: String?;
	
	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
		if let enumValue = json["AdaptationRequest"].object as? Int
		{
			self.adaptationRequest = AdaptationDetailValue(rawValue: enumValue);
		}
		self.description = json["Description"].object as? String;
		
		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	

	
		dictionary["AdaptationRequest"] = self.adaptationRequest?.rawValue;
	
	

	
		dictionary["Description"] = self.description;
	
	
		
		
		
		return dictionary;
	}
}

	