//
// AssociationDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class AssociationDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	var name: String?;
	var description: String?;
	var type: AssociationType?;
	var cardinalityOrigin: CardinalityType?;
	var cardinalityTarget: CardinalityType?;
	
	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
		self.name = json["Name"].object as? String;
		self.description = json["Description"].object as? String;
		if let enumValue = json["Type"].object as? Int
		{
			self.type = AssociationType(rawValue: enumValue);
		}
		if let enumValue = json["CardinalityOrigin"].object as? Int
		{
			self.cardinalityOrigin = CardinalityType(rawValue: enumValue);
		}
		if let enumValue = json["CardinalityTarget"].object as? Int
		{
			self.cardinalityTarget = CardinalityType(rawValue: enumValue);
		}
		
		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	

	
		dictionary["Name"] = self.name;
	
	

	
		dictionary["Description"] = self.description;
	
	

	
		dictionary["Type"] = self.type?.rawValue;
	
	

	
		dictionary["CardinalityOrigin"] = self.cardinalityOrigin?.rawValue;
	
	

	
		dictionary["CardinalityTarget"] = self.cardinalityTarget?.rawValue;
	
	
		
		
		
		return dictionary;
	}
}

	