//
// ComunicationDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class ComunicationDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	var severity: SeverityEvent?;
	var message: String?;
	var sendDate: NSDate?;
	
	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
		if let enumValue = json["Severity"].object as? Int
		{
			self.severity = SeverityEvent(rawValue: enumValue);
		}
		self.message = json["Message"].object as? String;
	
		self.sendDate = NSDate.initFromString(json["SendDate"].object as? String);
		
		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	

	
		dictionary["Severity"] = self.severity?.rawValue;
	
	

	
		dictionary["Message"] = self.message;
	
	

	
		dictionary["SendDate"] = self.sendDate?.toString();
	
	
		
		
		
		return dictionary;
	}
}

	