//
// PatientDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class PatientDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	var name: String?;
	var description: String?;
	
	/* Rol: Patient o--> PatientProfile */
	var patientProfile: PatientProfileDTOA?;

	/* Rol: Patient o--> User */
	var userData: UserDTOA?;

	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
		self.name = json["Name"].object as? String;
		self.description = json["Description"].object as? String;
		
		if (json["PatientProfile"] != JSON.null)
		{
			self.patientProfile = PatientProfileDTOA(fromJSONObject: json["PatientProfile"]);
		}

		if (json["UserData"] != JSON.null)
		{
			self.userData = UserDTOA(fromJSONObject: json["UserData"]);
		}

		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	

	
		dictionary["Name"] = self.name;
	
	

	
		dictionary["Description"] = self.description;
	
	
		
		dictionary["PatientProfile"] = self.patientProfile?.toDictionary() ?? NSNull();

		dictionary["UserData"] = self.userData?.toDictionary() ?? NSNull();

		
		
		return dictionary;
	}
}

	